const extendedScreens = {
  'livechat-chat-page-sharing': {
    title: 'LiveChat Chat Page Sharing',
    summary: 'Shareable hosted chat page with social and QR sharing entries.',
    route: '/settings/chat-page',
    section: 'Settings',
    assertions: [
      'Chat with customers wherever they are',
      'Share on X',
      'Share on Facebook',
      'Share QR code',
    ],
    controls: ['Customize', 'Copy'],
    state: 'Observed read-only screen state.',
  },
  'livechat-widget-language': {
    title: 'LiveChat Widget Language',
    summary: 'Widget language and customer-facing text labels.',
    route: '/settings/language',
    section: 'Settings',
    assertions: [
      'English',
      'Welcome message',
      'Default customer name',
      'Message placeholder',
      'Offline info',
      'Queued customer info',
    ],
    controls: ['English', 'Welcome message', 'Message placeholder'],
    state: 'Observed read-only screen state.',
  },
  'livechat-widget-availability': {
    title: 'LiveChat Widget Availability',
    summary: 'Availability rule selector for when customers can start a chat.',
    route: '/settings/availability',
    section: 'Settings',
    assertions: [
      'Customers can start a chat',
      'Always',
      'Only when agents are accepting chats',
      'What happens when',
    ],
    controls: ['Customize'],
    state: 'Observed read-only screen state.',
  },
  'livechat-welcome-screen': {
    title: 'LiveChat Welcome Screen',
    summary: 'Welcome screen editor with logo, channels, knowledge, and custom link sections.',
    route: '/settings/welcome-screen',
    section: 'Settings',
    assertions: [
      'Show logo',
      'Other channels',
      'KnowledgeBase',
      'HelpDesk',
      'Custom links',
      'Show welcome screen',
    ],
    controls: ['Welcome text', 'Customize', 'Go to marketplace', 'Install', 'Add links'],
    state: 'Observed read-only screen state.',
  },
  'livechat-pre-chat-form-builder': {
    title: 'LiveChat Pre-chat Form Builder',
    summary: 'Pre-chat form builder with message and required-field controls.',
    route: '/settings/pre-chat-form',
    section: 'Settings',
    assertions: [
      'Pre-chat form',
      'Show pre-chat form after campaign',
      'Name',
      'E-mail',
      'Start the chat',
    ],
    controls: ['Message', 'Required', 'Label', 'Add element'],
    state: 'Observed read-only screen state.',
  },
  'livechat-ask-for-email': {
    title: 'LiveChat Ask for Email',
    summary: 'Email collection timing choices for unattended or offline chat states.',
    route: '/settings/ask-for-email',
    section: 'Settings',
    assertions: [
      'Set up ask for email',
      'When not responding',
      'When offline',
      'Don’t send anything',
    ],
    controls: ['When not responding', 'When offline', 'Don’t send anything'],
    state: 'Observed read-only screen state.',
  },
  'livechat-post-chat-form': {
    title: 'LiveChat Post-chat Form',
    summary: 'Post-chat form configuration surface with a preview-focused state.',
    route: '/settings/post-chat-form',
    section: 'Settings',
    assertions: ['Post-chat form'],
    controls: [],
    state: 'Observed read-only screen state.',
  },
  'livechat-ticket-form': {
    title: 'LiveChat Ticket Form',
    summary: 'Ticket handoff form with a HelpDesk product boundary.',
    route: '/settings/ticket-form',
    section: 'Settings',
    assertions: ['Resolve customer cases through HelpDesk tickets', 'Your name', 'E-mail'],
    controls: ['Enable HelpDesk boosters', 'Next'],
    state: 'Observed read-only screen state.',
  },
  'livechat-eye-catcher-editor': {
    title: 'LiveChat Eye-catcher Editor',
    summary: 'Eye-catcher visibility and position editor.',
    route: '/settings/eye-catcher',
    section: 'Settings',
    assertions: ['Show eye-catcher', 'Reset position'],
    controls: ['Cancel', 'Reset position'],
    state: 'Observed read-only screen state.',
  },
  'livechat-chat-buttons-empty': {
    title: 'LiveChat Chat Buttons',
    summary: 'Chat button management screen with an empty inventory call to action.',
    route: '/settings/chat-buttons',
    section: 'Settings',
    assertions: ['Manage chat buttons'],
    controls: ['Create chat button', 'Install'],
    state: 'Observed read-only screen state.',
  },
  'livechat-quality-showcase-locked': {
    title: 'LiveChat Quality Showcase',
    summary: 'Locked quality badge and share page boundary.',
    route: '/settings/quality-badge',
    section: 'Settings',
    assertions: ['Publish Quality page', 'Share on X', 'Share on Facebook', 'Quality badge locked'],
    controls: ['Copy'],
    state: 'Observed read-only screen state.',
  },
  'livechat-tags-empty': {
    title: 'LiveChat Tags Manager',
    summary: 'Empty tags management screen.',
    route: '/settings/tags',
    section: 'Settings',
    assertions: ['Manage tags'],
    controls: ['Create tag'],
    state: 'Observed read-only screen state.',
  },
  'livechat-sales-tracker-empty': {
    title: 'LiveChat Sales Tracker',
    summary: 'Empty sales tracker management screen.',
    route: '/settings/sales-tracker',
    section: 'Settings',
    assertions: ['Manage sales trackers'],
    controls: ['New sales tracker'],
    state: 'Observed read-only screen state.',
  },
  'livechat-chat-assignment': {
    title: 'LiveChat Chat Assignment',
    summary: 'Assignment mode selector for automatic distribution or manual selection.',
    route: '/settings/chats-assignment',
    section: 'Settings',
    assertions: [
      'Choose how chats are distributed',
      'Auto assignment',
      'Manual selection',
      'Shortcuts to helpful stuff',
    ],
    controls: ['Auto assignment', 'Manual selection'],
    state: 'Observed read-only screen state.',
  },
  'livechat-transcript-forwarding': {
    title: 'LiveChat Transcript Forwarding',
    summary: 'Email forwarding destination for chat transcripts.',
    route: '/settings/archives-forwarding',
    section: 'Settings',
    assertions: ['Forward all chat transcript to email'],
    controls: [],
    state: 'Observed read-only screen state.',
  },
  'livechat-file-sharing': {
    title: 'LiveChat File Sharing',
    summary: 'Audience toggles for agent and visitor file sharing.',
    route: '/settings/file-sharing',
    section: 'Settings',
    assertions: ['Enable file sharing for:', 'Agents', 'Visitors'],
    controls: ['Agents', 'Visitors'],
    state: 'Observed read-only screen state.',
  },
  'livechat-inactivity-timeouts': {
    title: 'LiveChat Inactivity Timeouts',
    summary: 'Three staged inactivity timing rules with unchanged save controls.',
    route: '/settings/inactivity-timeouts',
    section: 'Settings',
    assertions: [
      'transfer after 3 minutes',
      'make inactive after 10 minutes',
      'close after 15 minutes',
    ],
    controls: ['Save changes', 'Discard changes'],
    state: 'Observed read-only screen state.',
  },
  'livechat-trusted-domains-empty': {
    title: 'LiveChat Trusted Domains',
    summary: 'Trusted and detected domain inventory with zero observed entries.',
    route: '/settings/trusted-domains',
    section: 'Settings',
    assertions: ['Manage domains', 'Trusted (0)', 'Detected (0)', 'Detected domains'],
    controls: ['Add to trusted'],
    state: 'Observed read-only screen state.',
  },
  'livechat-banned-customers-empty': {
    title: 'LiveChat Banned Customers',
    summary: 'Empty banned customer inventory.',
    route: '/settings/banned-customers',
    section: 'Settings',
    assertions: ['You haven’t banned any customers yet'],
    controls: ['Ban customer'],
    state: 'Observed read-only screen state.',
  },
  'livechat-credit-card-masking': {
    title: 'LiveChat Credit Card Masking',
    summary: 'Credit card display and masking choice group.',
    route: '/settings/credit-cards-masking',
    section: 'Settings',
    assertions: ['Show customers credit card numbers', 'Mask customers credit card numbers'],
    controls: [
      'Show customers credit card numbers',
      'Mask customers credit card numbers',
      'Cancel',
    ],
    state: 'Observed read-only screen state.',
  },
  'livechat-login-settings': {
    title: 'LiveChat Login Settings',
    summary: 'Authentication method selection boundary for the team.',
    route: '/settings/login-settings',
    section: 'Settings',
    assertions: ['Choose authentication method for your team'],
    controls: [],
    state: 'Observed read-only screen state.',
  },
  'livechat-email-helpdesk-boundary': {
    title: 'LiveChat Email by HelpDesk',
    summary: 'HelpDesk trial promotion for email support inside LiveChat settings.',
    route: '/settings/helpdesk',
    section: 'Settings',
    assertions: ['Transform your email experience'],
    controls: ['Try 14-day HelpDesk trial'],
    state: 'Observed read-only screen state.',
  },
  'livechat-facebook-messenger-boundary': {
    title: 'LiveChat Facebook Messenger Channel',
    summary: 'Facebook Messenger channel connection boundary.',
    route: '/settings/facebook-messenger',
    section: 'Settings',
    assertions: ['Accept chats from Facebook Messenger'],
    controls: [],
    state: 'Observed read-only screen state.',
  },
  'livechat-apple-messages-boundary': {
    title: 'LiveChat Apple Messages Channel',
    summary: 'Apple Messages for Business pricing and help boundary.',
    route: '/settings/apple-messages-for-business',
    section: 'Settings',
    assertions: ['Be right where communication happens'],
    controls: ['Open Help Center', 'View pricing plans'],
    state: 'Observed read-only screen state.',
  },
  'livechat-chatbots-empty': {
    title: 'LiveChat Chatbots',
    summary: 'Embedded chatbot workspace with an add-chatbot empty state.',
    route: '/automate/chatbots',
    section: 'Automate',
    assertions: ['Automate your customer service', 'Add chatbot', 'Add new chatbot', 'Name'],
    controls: ['Add chatbot', 'Add new chatbot'],
    state: 'Observed read-only screen state.',
  },
  'livechat-knowledge-hub-empty': {
    title: 'LiveChat Knowledge Hub',
    summary: 'Zero-source knowledge hub with website and PDF source actions.',
    route: '/automate/knowledge-hub/all-sources',
    section: 'Automate',
    assertions: ['Websites', 'PDF', 'All sources 0', 'Websites 0', 'PDF files 0'],
    controls: ['Tell me more', 'Close banner', 'Add website', 'Add PDF File'],
    state: 'Observed read-only screen state.',
  },
  'livechat-suggested-responses': {
    title: 'LiveChat Suggested Responses',
    summary: 'Shared and private suggestion tabs with event-based suggestions.',
    route: '/automate/suggested-responses',
    section: 'Automate',
    assertions: [
      'Event-based suggestions',
      'How can you disable suggestions for yourself?',
      'chat started',
      'transferred',
      'idle',
      'rated good',
      'rated bad',
    ],
    controls: ['Shared', 'Private'],
    state: 'Observed read-only screen state.',
  },
  'livechat-one-time-campaigns-empty': {
    title: 'LiveChat One-time Campaigns',
    summary: 'Empty one-time campaign table with recurring and one-time tabs.',
    route: '/engage/campaigns/one-time',
    section: 'Engage',
    assertions: ['Campaigns', 'Recurring', 'One-time'],
    controls: ['Add new campaign'],
    state: 'Observed read-only screen state.',
  },
  'livechat-campaign-template-gallery': {
    title: 'LiveChat Campaign Template Gallery',
    summary: 'Campaign goal tabs and reusable campaign template cards.',
    route: '/engage/campaigns/recurring/templates',
    section: 'Engage',
    assertions: [
      'What’s your campaign goal?',
      'Greet and inform',
      'Promote and convert',
      'Generate Leads',
      'Personalize experience',
      'Hook leaving visitors',
      'Announce new products',
      'Share valuable resources',
    ],
    controls: [
      'Greet and inform',
      'Promote and convert',
      'Generate Leads',
      'Hook leaving visitors',
    ],
    state: 'Observed read-only screen state.',
  },
  'livechat-campaign-builder': {
    title: 'LiveChat Campaign Builder',
    summary: 'Two-step campaign builder with editable message elements and condition step.',
    route: '/engage/campaigns/recurring/add',
    section: 'Engage',
    assertions: [
      'Hook leaving visitors',
      'Editable elements',
      'Previous: select template',
      'Next: set conditions',
    ],
    controls: ['Add button', 'Previous', 'Next'],
    state: 'Observed read-only screen state.',
  },
  'livechat-saved-views-empty': {
    title: 'LiveChat Saved Report Views',
    summary: 'Empty saved report view inventory.',
    route: '/reports/saved-views',
    section: 'Reports',
    assertions: ['No saved reports views yet'],
    controls: ['Explore reports'],
    state: 'Observed read-only screen state.',
  },
  'livechat-dashboard-promo': {
    title: 'LiveChat Reports Dashboard',
    summary: 'Wall dashboard promotion and launch boundary.',
    route: '/reports/dashboard',
    section: 'Reports',
    assertions: ['wall dashboard'],
    controls: ['Open dashboard'],
    state: 'Observed read-only screen state.',
  },
  'livechat-chat-engagement-report': {
    title: 'LiveChat Chat Engagement Report',
    summary: 'Chat engagement analytics route with shared report controls.',
    route: '/reports/chat-engagement',
    section: 'Reports',
    assertions: ['Chat engagement'],
    controls: ['Save view', 'Add filter'],
    state: 'Observed read-only screen state.',
  },
  'livechat-missed-chats-report': {
    title: 'LiveChat Missed Chats Report',
    summary: 'Missed chat analytics route with filtering and export controls.',
    route: '/reports/missed-chats',
    section: 'Reports',
    assertions: ['Missed chats'],
    controls: ['Save view', 'Add filter', 'Export CSV'],
    state: 'Observed read-only screen state.',
  },
  'livechat-campaigns-report': {
    title: 'LiveChat Campaign Conversion Report',
    summary: 'Campaign conversion report with configuration and export boundaries.',
    route: '/reports/campaigns',
    section: 'Reports',
    assertions: ['Campaigns'],
    controls: ['Save view', 'Add filter', 'Go to campaigns', 'Export CSV', 'Edit'],
    state: 'Observed read-only screen state.',
  },
  'livechat-tags-usage-report': {
    title: 'LiveChat Tags Usage Report',
    summary: 'Tag usage analytics route with refresh control.',
    route: '/reports/tags-usage',
    section: 'Reports',
    assertions: ['Tags usage'],
    controls: ['Save view', 'Refresh'],
    state: 'Observed read-only screen state.',
  },
  'livechat-chat-ratings-report': {
    title: 'LiveChat Chat Ratings Report',
    summary: 'Chat satisfaction analytics route with refresh control.',
    route: '/reports/chat-ratings',
    section: 'Reports',
    assertions: ['Chat ratings'],
    controls: ['Save view', 'Refresh'],
    state: 'Observed read-only screen state.',
  },
  'livechat-availability-report': {
    title: 'LiveChat Availability Report',
    summary: 'Availability analytics route with reusable report filters.',
    route: '/reports/availability',
    section: 'Reports',
    assertions: ['Availability'],
    controls: ['Save view', 'Add filter'],
    state: 'Observed read-only screen state.',
  },
  'livechat-chat-forms-report': {
    title: 'LiveChat Chat Forms Report',
    summary: 'Chat forms analytics with an empty closed-question result state.',
    route: '/reports/chat-forms',
    section: 'Reports',
    assertions: ['No results for closed questions'],
    controls: ['Save view', 'Add filter', 'Configure pre-chat form'],
    state: 'Observed read-only screen state.',
  },
  'livechat-chat-duration-upgrade': {
    title: 'LiveChat Chat Duration Report',
    summary: 'Chat duration analytics plan upgrade boundary.',
    route: '/reports/chat-duration',
    section: 'Reports',
    assertions: ['Chat duration', 'Upgrade plan'],
    controls: ['Upgrade plan'],
    state: 'Observed read-only screen state.',
  },
  'livechat-agent-performance-upgrade': {
    title: 'LiveChat Agent Performance Report',
    summary: 'Agent performance analytics plan upgrade boundary.',
    route: '/reports/agent-performance',
    section: 'Reports',
    assertions: ['Agent performance', 'Upgrade plan'],
    controls: ['Upgrade plan'],
    state: 'Observed read-only screen state.',
  },
  'livechat-chat-response-times-upgrade': {
    title: 'LiveChat Response Times Report',
    summary: 'Chat response time analytics plan upgrade boundary.',
    route: '/reports/chat-response-times',
    section: 'Reports',
    assertions: ['Chat response times', 'Upgrade plan'],
    controls: ['Upgrade plan'],
    state: 'Observed read-only screen state.',
  },
  'livechat-staffing-prediction-upgrade': {
    title: 'LiveChat Staffing Prediction Report',
    summary: 'Staffing prediction plan upgrade boundary.',
    route: '/reports/staffing-prediction',
    section: 'Reports',
    assertions: ['Staffing prediction', 'Upgrade plan'],
    controls: ['Upgrade plan'],
    state: 'Observed read-only screen state.',
  },
  'livechat-activity-upgrade': {
    title: 'LiveChat Agent Activity Report',
    summary: 'Agent activity analytics plan upgrade boundary.',
    route: '/reports/activity',
    section: 'Reports',
    assertions: ['Activity', 'Upgrade plan'],
    controls: ['Upgrade plan'],
    state: 'Observed read-only screen state.',
  },
  'livechat-queued-visitors-report': {
    title: 'LiveChat Queued Visitors Report',
    summary: 'Queued visitor report with filter and export controls.',
    route: '/reports/queued-visitors',
    section: 'Reports',
    assertions: ['Queued visitors'],
    controls: ['Save view', 'Add filter', 'Export CSV'],
    state: 'Observed read-only screen state.',
  },
  'livechat-queue-abandonment-empty': {
    title: 'LiveChat Queue Abandonment Report',
    summary: 'Queue abandonment report with a no-abandonment empty state.',
    route: '/reports/queue-abandonment',
    section: 'Reports',
    assertions: ['No customers left the queue in the set time period'],
    controls: ['Save view', 'Add filter'],
    state: 'Observed read-only screen state.',
  },
  'livechat-top-customer-questions': {
    title: 'LiveChat Top Customer Questions',
    summary: 'Top customer questions analytics shell.',
    route: '/reports/top-customer-questions',
    section: 'Reports',
    assertions: ['Top customer questions'],
    controls: [],
    state: 'Observed read-only screen state.',
  },
  'livechat-alerts-report': {
    title: 'LiveChat Alerts Report',
    summary: 'Alerts analytics shell.',
    route: '/reports/alerts',
    section: 'Reports',
    assertions: ['Alerts'],
    controls: [],
    state: 'Observed read-only screen state.',
  },
  'livechat-report-goals-empty': {
    title: 'LiveChat Report Goals',
    summary: 'Empty goal report with a create-goal boundary.',
    route: '/reports/goals',
    section: 'Reports',
    assertions: ['You don’t have any Goals set up'],
    controls: ['Save view', 'Add filter', 'Create a Goal'],
    state: 'Observed read-only screen state.',
  },
  'livechat-sales-report': {
    title: 'LiveChat Sales Report',
    summary: 'Sales analytics route with a refresh control.',
    route: '/reports/sales',
    section: 'Reports',
    assertions: ['Sales'],
    controls: ['Save view', 'Refresh'],
    state: 'Observed read-only screen state.',
  },
  'livechat-generate-report-upgrade': {
    title: 'LiveChat Generate Report',
    summary: 'Raw report generation plan upgrade boundary.',
    route: '/reports/generate-report',
    section: 'Reports',
    assertions: ['Generate report', 'Upgrade plan'],
    controls: ['Upgrade plan'],
    state: 'Observed read-only screen state.',
  },
  'livechat-scheduled-reports-upgrade': {
    title: 'LiveChat Scheduled Reports',
    summary: 'Scheduled report delivery plan upgrade boundary.',
    route: '/reports/scheduled-reports',
    section: 'Reports',
    assertions: ['Scheduled reports', 'Upgrade plan'],
    controls: ['Upgrade plan'],
    state: 'Observed read-only screen state.',
  },
  'livechat-reviews-empty': {
    title: 'LiveChat Reviews',
    summary: 'Empty reviews screen with a marketer invitation boundary.',
    route: '/reports/reviews',
    section: 'Reports',
    assertions: ['No reviews yet'],
    controls: ['Invite marketer'],
    state: 'Observed read-only screen state.',
  },
  'livechat-marketplace-app-detail': {
    title: 'LiveChat Marketplace App Detail',
    summary:
      'Marketplace app detail with overview, features, benefits, terms, reviews, and support sections.',
    route: 'Embedded marketplace path /apps/chatbot/',
    section: 'Apps',
    assertions: [
      'ChatBot',
      'Overview',
      'Key Features',
      'Benefits',
      'App Terms',
      'Reviews',
      'Support',
      'Legal Terms',
      'Tutorial & Support',
    ],
    controls: ['App tutorial', 'Contact ChatBot'],
    state: 'Observed read-only screen state.',
  },
  'livechat-marketplace-cart': {
    title: 'LiveChat Marketplace Cart',
    summary: 'Marketplace cart route observed without a rendered cart inventory.',
    route: '/apps/marketplace/cart',
    section: 'Apps',
    assertions: ['Cart', 'Go to Cart'],
    controls: ['Go to Cart'],
    state:
      'The shell and embedded cart route were observed. Cart contents did not render in the captured state.',
  },
  'livechat-profile-menu': {
    title: 'LiveChat Profile Menu',
    summary: 'Compact profile menu with availability and download-app entries.',
    route: '/apps/marketplace/cart',
    section: 'Application Layout',
    assertions: ['My Profile', 'Accept chats', 'Download apps'],
    controls: ['Accept chats', 'Download apps'],
    state: 'Observed read-only screen state.',
  },
  'livechat-billing-navigation': {
    title: 'LiveChat Billing Navigation',
    summary:
      'Billing shell with Subscription, Invoices, and Account details tabs plus an installed-applications load error.',
    route: '/subscription',
    section: 'Billing',
    assertions: [
      'Billing',
      'Subscription',
      'Invoices',
      'Account details',
      'Unable to load installed applications',
    ],
    controls: ['Subscription', 'Invoices', 'Account details'],
    state: 'Observed read-only screen state.',
  },
  'livechat-report-filter-toolbar': {
    title: 'LiveChat Report Filter Toolbar',
    summary: 'Reusable report toolbar with Save view and Add filter actions.',
    route: 'Shared across authenticated report routes',
    section: 'Reports',
    assertions: ['Save view', 'Add filter'],
    controls: ['Save view', 'Add filter'],
    state: 'Observed read-only screen state.',
  },
  'livechat-report-export-control': {
    title: 'LiveChat Report Export Control',
    summary: 'Export CSV action positioned alongside report filters.',
    route: 'Shared across /reports/missed-chats, /reports/campaigns and /reports/queued-visitors',
    section: 'Reports',
    assertions: ['Export CSV', 'Save view'],
    controls: ['Export CSV'],
    state: 'Observed read-only screen state.',
  },
  'livechat-report-upgrade-boundary': {
    title: 'LiveChat Report Upgrade Boundary',
    summary: 'Reusable locked-report state that directs the user to upgrade.',
    route: 'Shared across plan-locked report routes',
    section: 'Reports',
    assertions: ['Upgrade plan'],
    controls: ['Upgrade plan'],
    state: 'Observed read-only screen state.',
  },
  'livechat-settings-choice-group': {
    title: 'LiveChat Settings Choice Group',
    summary: 'Reusable radio, checkbox, or segmented choice group for configuration screens.',
    route: 'Shared across availability, assignment, file sharing, masking and login settings',
    section: 'Settings',
    assertions: ['Current choice', 'Alternative choice'],
    controls: ['Option A', 'Option B'],
    state:
      'The reconstruction represents the repeated choice-group structure with fictional labels.',
  },
  'livechat-empty-state-call-to-action': {
    title: 'LiveChat Empty State Call to Action',
    summary: 'Centered empty-state message with one guarded primary action.',
    route: 'Shared across tags, sales trackers, banned customers, campaigns, goals and reviews',
    section: 'Patterns',
    assertions: ['Empty-state heading', 'Primary action'],
    controls: ['Primary action'],
    state: 'Observed read-only screen state.',
  },
  'livechat-channel-connection-boundary': {
    title: 'LiveChat Channel Connection Boundary',
    summary: 'Channel promotion or connection boundary with product-specific next actions.',
    route: 'Shared across HelpDesk, Facebook Messenger and Apple Messages settings',
    section: 'Settings',
    assertions: ['Channel heading', 'Connection or pricing action'],
    controls: ['Inspect channel'],
    state: 'Observed read-only screen state.',
  },
} as const;

export type LivechatExtendedVariant = keyof typeof extendedScreens;

export const livechatExtendedEntries: Array<
  [string, LivechatExtendedVariant, string, Array<[string, string, string?]>]
> = Object.entries(extendedScreens).map(([variant, screen]) => [
  variant,
  variant as LivechatExtendedVariant,
  screen.title,
  [['default', screen.summary]],
]);

export function isLivechatExtendedVariant(value: string): value is LivechatExtendedVariant {
  return value in extendedScreens;
}

export function livechatExtendedSection(variant: LivechatExtendedVariant): string {
  return extendedScreens[variant].section;
}

export function livechatExtendedScreen(variant: LivechatExtendedVariant) {
  return extendedScreens[variant];
}
