import { useState } from 'react';
import { FramerPrimary } from '../framer-primary/FramerPrimary';
import styles from './screens.module.css';

export type FramerScreenKind = 'workspace' | 'search-sort' | 'settings' | 'editor' | 'navigation' | 'insertion' | 'layout' | 'inspector' | 'agent' | 'cms' | 'localization' | 'analytics' | 'seo' | 'integrations' | 'publication' | 'preview';
interface Props { screen: FramerScreenKind; initialState?: string; disabled?: boolean }
export function FramerScreen({ screen, initialState = 'default', disabled = false }: Props) {
  const [tab, setTab] = useState(initialState === 'fonts' ? 'Fonts' : initialState === 'credits' ? 'Credits' : initialState === 'performance' ? 'Performance' : initialState === 'code' ? 'Code' : initialState === 'versions' ? 'Versions' : initialState === 'fields' ? 'Fields' : initialState === 'assets' ? 'Assets' : initialState === 'layers' ? 'Layers' : initialState === 'forms' ? 'Forms' : initialState === 'page' ? 'Home' : 'General');
  const [archive, setArchive] = useState(initialState === 'archive');
  const [sortOpen, setSortOpen] = useState(initialState === 'sort-open');
  const [sort, setSort] = useState('Last viewed by me');
  const [notice, setNotice] = useState('');
  const [selected, setSelected] = useState(initialState === 'selected' || initialState === 'scroll');
  const notify = (action: string) => setNotice(`${action}: fictional local simulation. No provider request.`);
  const nav = (labels: string[]) => <nav className={styles.tabs} aria-label="Screen sections">{labels.map(label => <button key={label} aria-pressed={tab === label} onClick={() => setTab(label)}>{label}</button>)}</nav>;
  const inspector = <FramerPrimary kind="dimension" initialState={initialState === 'scroll' ? 'scroll' : 'default'} disabled={disabled} />;
  const agent = <FramerPrimary kind="prompt" disabled={disabled} />;
  return <section className={styles.root} aria-label={`Framer ${screen} screen reconstruction`}>
    <header><strong>Northstar Studio · Sample Landing</strong><span>RECONSTRUCTION · fictional data</span></header>
    <fieldset disabled={disabled}>
      {(screen === 'workspace' || screen === 'search-sort') && <div className={styles.workspace}><aside><h3>Workspace</h3><button onClick={() => setArchive(false)} aria-pressed={!archive}>All</button><button onClick={() => setArchive(true)} aria-pressed={archive}>Archive</button><button onClick={() => notify('New folder information')}>New folder…</button><button onClick={() => notify('Team invitation information')}>Invite your team</button></aside><main><div className={styles.bar}><h2>{archive ? 'Archive' : 'All'}</h2><button aria-expanded={sortOpen} onClick={() => setSortOpen(v => !v)}>{sort}</button><button onClick={() => notify('New project information')}>New project</button></div>{sortOpen && <div className={styles.menu} role="menu">{['Last viewed by me', 'Last edited', 'Alphabetically'].map(label => <button role="menuitem" key={label} onClick={() => { setSort(label); setSortOpen(false); }}>{label}</button>)}</div>}{archive ? <div className={styles.empty}><h3>No archived projects</h3><p>All archived projects will be listed here.</p></div> : screen === 'search-sort' ? <FramerPrimary kind="search" initialState={initialState === 'empty-results' ? 'empty-results' : 'default'} /> : <FramerPrimary kind="card" initialState={initialState === 'loading' ? 'loading' : 'default'} />}</main></div>}
      {screen === 'editor' && <><div className={styles.bar}><label>View<select aria-label="Editor view" defaultValue="Canvas" onChange={e => notify(`View ${e.target.value}`)}>{['Canvas', 'CMS', 'Localization', 'Analytics', 'Settings'].map(mode => <option key={mode}>{mode}</option>)}</select></label><button onClick={() => notify('Preview entry')}>Preview</button><button onClick={() => notify('Invitation information')}>Invite</button><button onClick={() => notify('Publication information')}>Publish information</button></div>{initialState === 'loading' ? <p role="status">Loading editor…</p> : <div className={styles.editor}><aside>{nav(['Pages', 'Layers', 'Assets'])}<h3>{tab === 'General' ? 'Pages' : tab}</h3><p>{tab === 'Assets' ? 'Templates · Components · Styles · Vectors · Code' : 'Home · Desktop · Primary'}</p></aside><div className={styles.canvas}><button className={styles.breakpoint} aria-pressed={selected} onClick={() => setSelected(v => !v)}>Desktop · 25%</button><div className={`${styles.blank} ${selected ? styles.selected : ''}`} /></div><aside>{selected ? inspector : agent}</aside></div>}</>}
      {screen === 'navigation' && <>{nav(['Pages', 'Layers', 'Assets'])}<div className={styles.panel}>{(tab === 'General' || tab === 'Pages') ? <><h3>Design</h3><button onClick={() => notify('Design page information')}>Add design page</button><h3>Pages</h3><button onClick={() => notify('Page information')}>Add page</button><p>Home</p></> : tab === 'Layers' ? <><label>Page<select defaultValue="Home"><option>Home</option></select></label><p>Desktop <small>Primary</small></p></> : ['Templates', 'Components', 'Styles', 'Vectors', 'Code'].map(label => <div className={styles.bar} key={label}><h3>{label}</h3><button onClick={() => notify(`Add ${label}`)}>Add {label.toLowerCase()}</button></div>)}</div></>}
      {screen === 'insertion' && <FramerPrimary kind="insert" initialState={initialState} disabled={disabled} />}
      {screen === 'layout' && <FramerPrimary kind="layout" initialState={initialState} disabled={disabled} />}
      {screen === 'inspector' && <><div className={styles.bar}><h2>Style</h2><button aria-pressed={selected} onClick={() => setSelected(v => !v)}>{selected ? 'Clear selection' : 'Select Desktop'}</button></div>{selected ? <><p>Align left · center · right · top · middle · bottom</p>{inspector}{['Layout', 'Overlays', 'Cursor', 'Effects', 'Styles', 'Code overrides'].map(label => <details key={label}><summary>{label}</summary><p>Configuration not observed. Local placeholder only.</p></details>)}<label>Fill<input defaultValue="FFFFFF" /></label></> : <><h3>Typography</h3><label>Base font size<input type="number" defaultValue={16} /></label><p>Template</p></>}</>}
      {screen === 'agent' && agent}
      {screen === 'cms' && <>{nav(['Collections', 'Fields', 'Plugins'])}<div className={styles.split}><aside>{tab === 'Fields' ? ['Title', 'Slug', 'Image', 'Content', 'Featured'].map(label => <p key={label}>{label}</p>) : <><h3>Collections</h3><button onClick={() => notify('Collection creation information')}>Add collection</button></>}</aside><main><h2>Collections</h2><p>Generate a new collection with the Agent, or import and sync external data with plugins.</p>{agent}</main></div></>}
      {screen === 'localization' && <div className={styles.split}><aside><h3>Locales</h3><p>Plugins</p><FramerPrimary kind="usage" disabled={disabled} /></aside><main><h2>Localization</h2><p>Add a locale to start localizing your site.</p><FramerPrimary kind="locale" initialState={initialState === 'dialog' ? 'default' : 'closed'} disabled={disabled} /></main></div>}
      {screen === 'analytics' && <div className={styles.editor}><aside><h3>Analytics</h3><p>Overview</p><h3>Funnels</h3><h3>A/B tests</h3><button onClick={() => notify('Refresh simulation')}>Refresh</button></aside><main><FramerPrimary kind="gate" disabled={disabled} /></main><aside>{agent}</aside></div>}
      {screen === 'settings' && <>{nav(['General', 'Fonts', 'Credits'])}{tab === 'Fonts' ? <><h2>Fonts</h2><p>Workspace admins and editors can upload custom fonts to use in projects.</p><button onClick={() => notify('Font upload information')}>Add font information</button></> : tab === 'Credits' ? <FramerPrimary kind="usage" /> : <><h2>General</h2><label>Workspace name<input defaultValue="Northstar Studio" /></label><h3>Permissions</h3>{['Invite links', 'Workspace recommendations', 'Project transfers', 'AI model training'].map(label => <label key={label}><input type="checkbox" defaultChecked={label !== 'Workspace recommendations'} />{label} · fictional defaults</label>)}<p>Workspace access · Upgrade</p><p>Project access · Upgrade</p><h3>Danger zone</h3><p>You can’t delete your only workspace.</p><button disabled>Delete workspace</button></>}</>}
      {screen === 'seo' && <>{nav(['General', 'Home'])}<FramerPrimary kind="seo" disabled={disabled} />{tab === 'General' && <><h3>Accessibility</h3><label><input type="checkbox" />Reduced motion</label><label><input type="checkbox" />Preserve URL parameters</label><label><input type="checkbox" defaultChecked />RTL layout direction</label><h3>Site images</h3><p>Favicon 64 × 64 · Social preview 1200 × 630 · Apple touch icon 180 × 180</p><h3>Google Analytics</h3><input aria-label="Tracking ID" placeholder="Fictional tracking ID only" /><h3>API keys · Beta</h3><button onClick={() => notify('API-key information')}>API-key information</button><button disabled>Unpublish</button></>}</>}
      {screen === 'integrations' && <>{nav(['Forms', 'Performance', 'Code'])}{tab === 'Performance' ? <><h2>Performance</h2><label>Font loading<select><option>System font first</option></select></label><label><input type="checkbox" defaultChecked />Optimize third-party scripts</label><p>Images · Fonts · JavaScript · Network</p><p>Enabled labels reproduce provider copy, not measured performance.</p></> : tab === 'Code' ? <><h2>Custom code</h2><p>Add custom scripts that run on selected pages.</p><button onClick={() => notify('Script setup information')}>Add script information</button></> : <><h2>Form settings</h2><FramerPrimary kind="gate" initialState="upgrade" /><h3>Google account</h3><p>Connect a Google account to send form data to a Sheet.</p><button onClick={() => notify('Google connection information')}>Connection information</button></>}</>}
      {screen === 'publication' && <>{nav(['Domains', 'Versions'])}{tab === 'Versions' ? <><h2>Preview</h2><p>Connect a custom domain to enable this setting.</p><h2>Versions</h2><p>Publish your project to generate a version.</p><button onClick={() => notify('Domain prerequisite information')}>Domain information</button></> : <FramerPrimary kind="gate" initialState="domain" />}</>}
      {screen === 'preview' && <FramerPrimary kind="viewport" initialState={initialState} disabled={disabled} />}
    </fieldset>
    {notice && <p className={styles.notice} role="status">{notice}</p>}
  </section>;
}
