import { useState } from 'react';
import styles from './framer.module.css';

export type FramerKind = 'search' | 'card' | 'mode' | 'insert' | 'layout' | 'dimension' | 'prompt' | 'locale' | 'usage' | 'seo' | 'gate' | 'viewport';
export interface FramerPrimaryProps { kind: FramerKind; initialState?: string; disabled?: boolean }

const modes = ['Canvas', 'CMS', 'Localization', 'Analytics', 'Settings'];
const tools = ['Frame', 'Stack', 'Grid', 'Masonry', 'Image', 'Video'];
const categories = ['Icons', 'Shaders', 'Media', 'Forms', 'Interactive', 'Social', 'Utility', 'Creative'];
const items: Record<string, string[]> = { Forms: ['Forms', 'Typeform', 'Waitlist', 'Calendly'], Interactive: ['Ticker', 'Carousel', 'Slideshow', 'Cookie Banner', 'Search', 'Locale Selector'] };

export function FramerPrimary({ kind, initialState = 'default', disabled = false }: FramerPrimaryProps) {
  const [open, setOpen] = useState(initialState === 'open');
  const [selection, setSelection] = useState(kind === 'insert' ? (initialState === 'collections' ? 'Collections' : initialState === 'interactive' ? 'Interactive' : 'Forms') : kind === 'mode' && initialState === 'cms' ? 'CMS' : kind === 'locale' && initialState === 'selected' ? 'English' : '');
  const [text, setText] = useState(initialState === 'empty-results' ? 'no-match' : initialState === 'draft' ? 'Create a fictional landing page' : '');
  const [width, setWidth] = useState(initialState === 'narrow' ? '390' : kind === 'dimension' ? '1200' : '1088');
  const [height, setHeight] = useState('1000');
  const [title, setTitle] = useState(initialState === 'custom' ? 'Northstar Studio' : '');
  const [description, setDescription] = useState(initialState === 'custom' ? 'A fictional creative studio.' : '');
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  const [active, setActive] = useState(initialState === 'selected');
  const notice = (value: string) => setMessage(`${value} — local simulation only.`);
  const updateDimension = (value: string, setter: (value: string) => void) => { setter(value); setError(''); };
  const validate = () => { if (![width, height].every(v => Number.isFinite(Number(v)) && Number(v) > 0 && v.trim() !== '')) setError('Enter a positive dimension. Reconstructed validation.'); };

  return <section className={styles.root} aria-label={`Framer ${kind} fixture`}>
    <div className={styles.evidence}>RECONSTRUCTION · fictional local fixture</div>
    <fieldset disabled={disabled} className={styles.body}>
      {kind === 'search' && <>
        <div className={styles.row}><label className={styles.grow}>Search projects<input aria-label="Search projects" placeholder="Search…" value={text} onChange={e => setText(e.target.value)} /></label>{text && <button onClick={() => setText('')}>Clear search filter</button>}</div>
        {text && !'northstar landing'.includes(text.toLowerCase()) ? <div className={styles.empty}><strong>No results</strong><p>Try adjusting your search or browse workspaces.</p><button onClick={() => setText('')}>Close</button></div> : <div className={styles.result}>Northstar Landing <span>Free</span></div>}
      </>}
      {kind === 'card' && <button className={`${styles.card} ${active ? styles.selected : ''}`} aria-pressed={active} onClick={() => { setActive(v => !v); notice('Project selection'); }}>
        <span className={styles.thumbnail}>{initialState === 'loading' ? <span role="status">Loading thumbnail…</span> : 'N'}</span><strong>Northstar Landing</strong><span>Viewed recently <small>Free</small></span>
      </button>}
      {kind === 'mode' && <div className={styles.picker}><button aria-expanded={open} onClick={() => setOpen(v => !v)}>{selection || 'Canvas'} ▾</button>{open && <div role="menu" aria-label="Editor modes" onKeyDown={e => { if (e.key === 'Escape') setOpen(false); }}>{modes.map((mode, i) => <button role="menuitem" key={mode} disabled={(selection || 'Canvas') === mode} onClick={() => { setSelection(mode); setOpen(false); notice(`Mode ${mode}`); }}>{mode}<small>⌥ {i + 1}</small></button>)}</div>}</div>}
      {kind === 'insert' && <div className={styles.columns}><nav aria-label="Insertion categories"><small>Elements</small>{categories.map(category => <button key={category} aria-pressed={selection === category} onClick={() => setSelection(category)}>{category} ›</button>)}<small>CMS</small><button aria-pressed={selection === 'Collections'} onClick={() => setSelection('Collections')}>Collections ›</button></nav><div className={styles.grow}><h3>{selection}</h3>{selection === 'Collections' ? <p>Generate a new collection with the Agent, or import and sync external data with plugins.</p> : (items[selection] || ['Fictional item']).map(item => <button className={styles.tile} key={item} onClick={() => notice(`Selected ${item}`)}>{item}</button>)}</div></div>}
      {kind === 'layout' && <div className={styles.picker}><button aria-expanded={open} onClick={() => setOpen(v => !v)}>Layout ▾</button>{open && <div role="menu" aria-label="Layout tools" onKeyDown={e => { if (e.key === 'Escape') setOpen(false); }}>{tools.map((tool, i) => <button role="menuitem" key={tool} onClick={() => { setSelection(tool); setOpen(false); notice(`Tool ${tool}`); }}>{tool}<small>{['F', 'S', '⇧ G', '⇧ M', '⇧ I', '⇧ V'][i]}</small></button>)}</div>}{selection && <p>Selected tool: {selection}</p>}</div>}
      {kind === 'dimension' && <><h3>Breakpoint</h3><div className={styles.row}><label>Width<input aria-label="Breakpoint width" inputMode="numeric" value={width} onChange={e => updateDimension(e.target.value, setWidth)} onBlur={validate} aria-invalid={!!error} /></label><label>Sizing<select defaultValue="Fixed"><option>Fixed</option><option disabled>Relative</option><option disabled>Fill</option><option disabled>Fit content</option></select></label></div><div className={styles.row}><label>Height<input aria-label="Breakpoint height" inputMode="numeric" value={height} onChange={e => updateDimension(e.target.value, setHeight)} onBlur={validate} /></label><label>Overflow<select defaultValue={initialState === 'scroll' ? 'Scroll' : 'Clip'}><option>Clip</option><option>Visible</option><option>Hidden</option><option>Scroll</option></select></label></div><p>Edits affect this local inspector only.</p></>}
      {kind === 'prompt' && <><div className={styles.row}><h3>Agent</h3><button onClick={() => { setText(''); setMessage(''); }}>New chat</button></div><label>Prompt<textarea aria-label="Prompt" placeholder="Ask Framer…" value={text} onChange={e => setText(e.target.value)} /></label><div className={styles.row}><select aria-label="Model" defaultValue="Observed model label"><option>Observed model label</option><option>Fictional alternate</option></select><button className={styles.primary} disabled={!text.trim()} onClick={() => { notice('Prompt simulated'); setText(''); }}>Send</button></div><p>No AI service is called.</p></>}
      {kind === 'locale' && <>{initialState === 'closed' || message ? <button onClick={() => { setMessage(''); setOpen(true); }}>Add locale</button> : <div role="dialog" aria-label="Set default language"><h3>Set default language</h3><label>Default language<select aria-label="Default language" value={selection} onChange={e => setSelection(e.target.value)}><option value="">Default language</option>{['English', 'Afrikaans', 'Arabic', 'French'].map(language => <option key={language}>{language}</option>)}</select></label><p>Confirm the default language of your site before setting up localization.</p><div className={styles.row}><button onClick={() => notice('Canceled')}>Cancel</button><button disabled={!selection} className={styles.primary} onClick={() => notice('Language selection simulated')}>Confirm</button></div></div>}{open && initialState === 'closed' && !message && <div role="dialog" aria-label="Set default language"><label>Default language<select value={selection} onChange={e => setSelection(e.target.value)}><option value="">Choose language</option><option>English</option><option>French</option></select></label><button onClick={() => { setOpen(false); notice('Canceled'); }}>Cancel</button><button disabled={!selection} onClick={() => { setOpen(false); notice('Language selection simulated'); }}>Confirm</button></div>}</>}
      {kind === 'usage' && <><h3>Words</h3><div className={styles.row}><strong>{initialState === 'full' ? '5,000' : initialState === 'partial' ? '2,000' : '0'} / 5,000</strong><span>Fictional allowance</span></div><progress aria-label="Words used" max={5000} value={initialState === 'full' ? 5000 : initialState === 'partial' ? 2000 : 0} /><button onClick={() => notice('Upgrade information')}>Upgrade</button></>}
      {kind === 'seo' && <><label>Title<input aria-label="Page title" placeholder="Inherited from site" value={title} onChange={e => setTitle(e.target.value)} /></label><label>Description<textarea aria-label="Page description" placeholder="Inherited from site" value={description} onChange={e => setDescription(e.target.value)} /></label><div className={styles.serp}><small>northstar.example</small><h3>{title || 'My Framer Site'}</h3><p>{description || 'Made with Framer'}</p><small>{!title && !description ? 'Inherited site values' : 'Local page overrides'}</small></div><label className={styles.check}><input type="checkbox" defaultChecked={initialState !== 'hidden'} />Search engines</label><label className={styles.check}><input type="checkbox" defaultChecked />Site search</label></>}
      {kind === 'gate' && <div className={styles.empty}><h3>{initialState === 'domain' ? 'Domains' : initialState === 'upgrade' ? 'Campaign tracking' : 'Analytics'}</h3><p>{initialState === 'domain' ? 'First publish your website, then add a custom domain.' : initialState === 'upgrade' ? 'Upgrade to include campaign tags in form submissions.' : 'Publish your website to track and view insights.'}</p>{initialState === 'upgrade' && <label className={styles.check}><input type="checkbox" disabled />Campaign tracking</label>}<button className={styles.primary} onClick={() => notice('Prerequisite information')}>{initialState === 'upgrade' ? 'Upgrade' : 'Publication information'}</button></div>}
      {kind === 'viewport' && <><div className={styles.row}><button onClick={() => { setWidth('1088'); setHeight('1000'); setError(''); }}>Reset preview</button><label>W<input aria-label="Preview width" value={width} onChange={e => updateDimension(e.target.value, setWidth)} onBlur={validate} /></label><label>H<input aria-label="Preview height" value={height} onChange={e => updateDimension(e.target.value, setHeight)} onBlur={validate} /></label></div><div className={styles.previewStage}><div aria-label="Fictional page viewport" className={styles.page} style={{ width: Math.min(Math.max(Number(width) || 1, 1), 1400), minHeight: Math.min(Math.max(Number(height) || 1, 1), 500) }}><span>Fictional blank page</span></div></div><p>Preview dimensions are independent of project breakpoints.</p></>}
    </fieldset>
    {error && <p role="alert" className={styles.error}>{error}</p>}
    {message && <p role="status" className={styles.feedback}>{message}</p>}
  </section>;
}
