import type { PreviewRegistry } from '../types';
import { FramerPrimary } from './FramerPrimary';

export const framerPrimaryPreviews: PreviewRegistry = {
  'framer-project-search-field': {
    type: 'reconstructed', Component: FramerPrimary, label: 'Fictional local Framer primary component',
    evidence: 'Observed structural reference captured 2026-10-07. All rendered content and interactions are local reconstructions. Fixture titles distinguish observed structure from invented states. No provider requests or writes occur. Runtime verification covers fictional local fixtures only.',
    runtimeVerified: true,
    fixtures: [{"id": "default", "title": "OBSERVED structure: idle search", "props": {"kind": "search", "initialState": "default"}}, {"id": "empty-results", "title": "OBSERVED structure: no results", "props": {"kind": "search", "initialState": "empty-results"}}, {"id": "disabled", "title": "RECONSTRUCTION: disabled control", "props": {"kind": "search", "initialState": "disabled", "disabled": true}}],
    config: { viewports: [{ id: 'desktop', label: 'Desktop', width: 760 }, { id: 'narrow', label: 'Narrow', width: 390 }], toggles: [{ id: 'disabled', label: 'Interaction', onLabel: 'Disabled', offLabel: 'Enabled' }] },
    propsSchema: [{ name: 'kind', type: 'FramerKind', required: true, description: 'Selects an individual primary control.' }, { name: 'initialState', type: 'string', required: false, description: 'Initial fixture state. Unobserved states are labelled reconstruction.' }, { name: 'disabled', type: 'boolean', required: false, description: 'Disables local controls.' }],
  },
  'framer-project-thumbnail-card': {
    type: 'reconstructed', Component: FramerPrimary, label: 'Fictional local Framer primary component',
    evidence: 'Observed structural reference captured 2026-10-07. All rendered content and interactions are local reconstructions. Fixture titles distinguish observed structure from invented states. No provider requests or writes occur. Runtime verification covers fictional local fixtures only.',
    runtimeVerified: true,
    fixtures: [{"id": "default", "title": "OBSERVED structure: free project", "props": {"kind": "card", "initialState": "default"}}, {"id": "loading", "title": "OBSERVED structure: thumbnail loading", "props": {"kind": "card", "initialState": "loading"}}, {"id": "selected", "title": "RECONSTRUCTION: selected card", "props": {"kind": "card", "initialState": "selected"}}],
    config: { viewports: [{ id: 'desktop', label: 'Desktop', width: 760 }, { id: 'narrow', label: 'Narrow', width: 390 }], toggles: [{ id: 'disabled', label: 'Interaction', onLabel: 'Disabled', offLabel: 'Enabled' }] },
    propsSchema: [{ name: 'kind', type: 'FramerKind', required: true, description: 'Selects an individual primary control.' }, { name: 'initialState', type: 'string', required: false, description: 'Initial fixture state. Unobserved states are labelled reconstruction.' }, { name: 'disabled', type: 'boolean', required: false, description: 'Disables local controls.' }],
  },
  'framer-editor-mode-menu': {
    type: 'reconstructed', Component: FramerPrimary, label: 'Fictional local Framer primary component',
    evidence: 'Observed structural reference captured 2026-10-07. All rendered content and interactions are local reconstructions. Fixture titles distinguish observed structure from invented states. No provider requests or writes occur. Runtime verification covers fictional local fixtures only.',
    runtimeVerified: true,
    fixtures: [{"id": "default", "title": "OBSERVED structure: closed Canvas", "props": {"kind": "mode", "initialState": "default"}}, {"id": "open", "title": "OBSERVED structure: expanded modes", "props": {"kind": "mode", "initialState": "open"}}, {"id": "cms", "title": "RECONSTRUCTION: CMS selected", "props": {"kind": "mode", "initialState": "cms"}}],
    config: { viewports: [{ id: 'desktop', label: 'Desktop', width: 760 }, { id: 'narrow', label: 'Narrow', width: 390 }], toggles: [{ id: 'disabled', label: 'Interaction', onLabel: 'Disabled', offLabel: 'Enabled' }] },
    propsSchema: [{ name: 'kind', type: 'FramerKind', required: true, description: 'Selects an individual primary control.' }, { name: 'initialState', type: 'string', required: false, description: 'Initial fixture state. Unobserved states are labelled reconstruction.' }, { name: 'disabled', type: 'boolean', required: false, description: 'Disables local controls.' }],
  },
  'framer-insertion-category-list': {
    type: 'reconstructed', Component: FramerPrimary, label: 'Fictional local Framer primary component',
    evidence: 'Observed structural reference captured 2026-10-07. All rendered content and interactions are local reconstructions. Fixture titles distinguish observed structure from invented states. No provider requests or writes occur. Runtime verification covers fictional local fixtures only.',
    runtimeVerified: true,
    fixtures: [{"id": "default", "title": "OBSERVED structure: Forms", "props": {"kind": "insert", "initialState": "default"}}, {"id": "interactive", "title": "OBSERVED structure: Interactive", "props": {"kind": "insert", "initialState": "interactive"}}, {"id": "collections", "title": "OBSERVED structure: empty Collections", "props": {"kind": "insert", "initialState": "collections"}}],
    config: { viewports: [{ id: 'desktop', label: 'Desktop', width: 760 }, { id: 'narrow', label: 'Narrow', width: 390 }], toggles: [{ id: 'disabled', label: 'Interaction', onLabel: 'Disabled', offLabel: 'Enabled' }] },
    propsSchema: [{ name: 'kind', type: 'FramerKind', required: true, description: 'Selects an individual primary control.' }, { name: 'initialState', type: 'string', required: false, description: 'Initial fixture state. Unobserved states are labelled reconstruction.' }, { name: 'disabled', type: 'boolean', required: false, description: 'Disables local controls.' }],
  },
  'framer-layout-tool-picker': {
    type: 'reconstructed', Component: FramerPrimary, label: 'Fictional local Framer primary component',
    evidence: 'Observed structural reference captured 2026-10-07. All rendered content and interactions are local reconstructions. Fixture titles distinguish observed structure from invented states. No provider requests or writes occur. Runtime verification covers fictional local fixtures only.',
    runtimeVerified: true,
    fixtures: [{"id": "default", "title": "OBSERVED structure: closed", "props": {"kind": "layout", "initialState": "default"}}, {"id": "open", "title": "OBSERVED structure: tool menu", "props": {"kind": "layout", "initialState": "open"}}, {"id": "disabled", "title": "RECONSTRUCTION: disabled trigger", "props": {"kind": "layout", "initialState": "disabled", "disabled": true}}],
    config: { viewports: [{ id: 'desktop', label: 'Desktop', width: 760 }, { id: 'narrow', label: 'Narrow', width: 390 }], toggles: [{ id: 'disabled', label: 'Interaction', onLabel: 'Disabled', offLabel: 'Enabled' }] },
    propsSchema: [{ name: 'kind', type: 'FramerKind', required: true, description: 'Selects an individual primary control.' }, { name: 'initialState', type: 'string', required: false, description: 'Initial fixture state. Unobserved states are labelled reconstruction.' }, { name: 'disabled', type: 'boolean', required: false, description: 'Disables local controls.' }],
  },
  'framer-breakpoint-dimension-field': {
    type: 'reconstructed', Component: FramerPrimary, label: 'Fictional local Framer primary component',
    evidence: 'Observed structural reference captured 2026-10-07. All rendered content and interactions are local reconstructions. Fixture titles distinguish observed structure from invented states. No provider requests or writes occur. Runtime verification covers fictional local fixtures only.',
    runtimeVerified: true,
    fixtures: [{"id": "default", "title": "OBSERVED structure: fixed dimensions", "props": {"kind": "dimension", "initialState": "default"}}, {"id": "scroll", "title": "RECONSTRUCTION: scroll overflow", "props": {"kind": "dimension", "initialState": "scroll"}}, {"id": "disabled", "title": "RECONSTRUCTION: disabled inspector", "props": {"kind": "dimension", "initialState": "disabled", "disabled": true}}],
    config: { viewports: [{ id: 'desktop', label: 'Desktop', width: 760 }, { id: 'narrow', label: 'Narrow', width: 390 }], toggles: [{ id: 'disabled', label: 'Interaction', onLabel: 'Disabled', offLabel: 'Enabled' }] },
    propsSchema: [{ name: 'kind', type: 'FramerKind', required: true, description: 'Selects an individual primary control.' }, { name: 'initialState', type: 'string', required: false, description: 'Initial fixture state. Unobserved states are labelled reconstruction.' }, { name: 'disabled', type: 'boolean', required: false, description: 'Disables local controls.' }],
  },
  'framer-agent-prompt-composer': {
    type: 'reconstructed', Component: FramerPrimary, label: 'Fictional local Framer primary component',
    evidence: 'Observed structural reference captured 2026-10-07. All rendered content and interactions are local reconstructions. Fixture titles distinguish observed structure from invented states. No provider requests or writes occur. Runtime verification covers fictional local fixtures only.',
    runtimeVerified: true,
    fixtures: [{"id": "default", "title": "OBSERVED structure: empty composer", "props": {"kind": "prompt", "initialState": "default"}}, {"id": "draft", "title": "RECONSTRUCTION: fictional draft", "props": {"kind": "prompt", "initialState": "draft"}}, {"id": "disabled", "title": "RECONSTRUCTION: disabled composer", "props": {"kind": "prompt", "initialState": "disabled", "disabled": true}}],
    config: { viewports: [{ id: 'desktop', label: 'Desktop', width: 760 }, { id: 'narrow', label: 'Narrow', width: 390 }], toggles: [{ id: 'disabled', label: 'Interaction', onLabel: 'Disabled', offLabel: 'Enabled' }] },
    propsSchema: [{ name: 'kind', type: 'FramerKind', required: true, description: 'Selects an individual primary control.' }, { name: 'initialState', type: 'string', required: false, description: 'Initial fixture state. Unobserved states are labelled reconstruction.' }, { name: 'disabled', type: 'boolean', required: false, description: 'Disables local controls.' }],
  },
  'framer-default-language-picker': {
    type: 'reconstructed', Component: FramerPrimary, label: 'Fictional local Framer primary component',
    evidence: 'Observed structural reference captured 2026-10-07. All rendered content and interactions are local reconstructions. Fixture titles distinguish observed structure from invented states. No provider requests or writes occur. Runtime verification covers fictional local fixtures only.',
    runtimeVerified: true,
    fixtures: [{"id": "default", "title": "OBSERVED structure: no language", "props": {"kind": "locale", "initialState": "default"}}, {"id": "selected", "title": "RECONSTRUCTION: selected English", "props": {"kind": "locale", "initialState": "selected"}}, {"id": "closed", "title": "RECONSTRUCTION: dismissed dialog", "props": {"kind": "locale", "initialState": "closed"}}],
    config: { viewports: [{ id: 'desktop', label: 'Desktop', width: 760 }, { id: 'narrow', label: 'Narrow', width: 390 }], toggles: [{ id: 'disabled', label: 'Interaction', onLabel: 'Disabled', offLabel: 'Enabled' }] },
    propsSchema: [{ name: 'kind', type: 'FramerKind', required: true, description: 'Selects an individual primary control.' }, { name: 'initialState', type: 'string', required: false, description: 'Initial fixture state. Unobserved states are labelled reconstruction.' }, { name: 'disabled', type: 'boolean', required: false, description: 'Disables local controls.' }],
  },
  'framer-word-usage-meter': {
    type: 'reconstructed', Component: FramerPrimary, label: 'Fictional local Framer primary component',
    evidence: 'Observed structural reference captured 2026-10-07. All rendered content and interactions are local reconstructions. Fixture titles distinguish observed structure from invented states. No provider requests or writes occur. Runtime verification covers fictional local fixtures only.',
    runtimeVerified: true,
    fixtures: [{"id": "default", "title": "OBSERVED structure: zero usage", "props": {"kind": "usage", "initialState": "default"}}, {"id": "partial", "title": "RECONSTRUCTION: partial usage", "props": {"kind": "usage", "initialState": "partial"}}, {"id": "full", "title": "RECONSTRUCTION: exhausted allowance", "props": {"kind": "usage", "initialState": "full"}}],
    config: { viewports: [{ id: 'desktop', label: 'Desktop', width: 760 }, { id: 'narrow', label: 'Narrow', width: 390 }], toggles: [{ id: 'disabled', label: 'Interaction', onLabel: 'Disabled', offLabel: 'Enabled' }] },
    propsSchema: [{ name: 'kind', type: 'FramerKind', required: true, description: 'Selects an individual primary control.' }, { name: 'initialState', type: 'string', required: false, description: 'Initial fixture state. Unobserved states are labelled reconstruction.' }, { name: 'disabled', type: 'boolean', required: false, description: 'Disables local controls.' }],
  },
  'framer-page-seo-result-preview': {
    type: 'reconstructed', Component: FramerPrimary, label: 'Fictional local Framer primary component',
    evidence: 'Observed structural reference captured 2026-10-07. All rendered content and interactions are local reconstructions. Fixture titles distinguish observed structure from invented states. No provider requests or writes occur. Runtime verification covers fictional local fixtures only.',
    runtimeVerified: true,
    fixtures: [{"id": "default", "title": "OBSERVED structure: inherited defaults", "props": {"kind": "seo", "initialState": "default"}}, {"id": "custom", "title": "RECONSTRUCTION: page overrides", "props": {"kind": "seo", "initialState": "custom"}}, {"id": "hidden", "title": "RECONSTRUCTION: search disabled", "props": {"kind": "seo", "initialState": "hidden"}}],
    config: { viewports: [{ id: 'desktop', label: 'Desktop', width: 760 }, { id: 'narrow', label: 'Narrow', width: 390 }], toggles: [{ id: 'disabled', label: 'Interaction', onLabel: 'Disabled', offLabel: 'Enabled' }] },
    propsSchema: [{ name: 'kind', type: 'FramerKind', required: true, description: 'Selects an individual primary control.' }, { name: 'initialState', type: 'string', required: false, description: 'Initial fixture state. Unobserved states are labelled reconstruction.' }, { name: 'disabled', type: 'boolean', required: false, description: 'Disables local controls.' }],
  },
  'framer-publication-upgrade-gate': {
    type: 'reconstructed', Component: FramerPrimary, label: 'Fictional local Framer primary component',
    evidence: 'Observed structural reference captured 2026-10-07. All rendered content and interactions are local reconstructions. Fixture titles distinguish observed structure from invented states. No provider requests or writes occur. Runtime verification covers fictional local fixtures only.',
    runtimeVerified: true,
    fixtures: [{"id": "default", "title": "OBSERVED structure: analytics prerequisite", "props": {"kind": "gate", "initialState": "default"}}, {"id": "domain", "title": "OBSERVED structure: domain prerequisite", "props": {"kind": "gate", "initialState": "domain"}}, {"id": "upgrade", "title": "OBSERVED structure: campaign upgrade", "props": {"kind": "gate", "initialState": "upgrade"}}],
    config: { viewports: [{ id: 'desktop', label: 'Desktop', width: 760 }, { id: 'narrow', label: 'Narrow', width: 390 }], toggles: [{ id: 'disabled', label: 'Interaction', onLabel: 'Disabled', offLabel: 'Enabled' }] },
    propsSchema: [{ name: 'kind', type: 'FramerKind', required: true, description: 'Selects an individual primary control.' }, { name: 'initialState', type: 'string', required: false, description: 'Initial fixture state. Unobserved states are labelled reconstruction.' }, { name: 'disabled', type: 'boolean', required: false, description: 'Disables local controls.' }],
  },
  'framer-preview-viewport-fields': {
    type: 'reconstructed', Component: FramerPrimary, label: 'Fictional local Framer primary component',
    evidence: 'Observed structural reference captured 2026-10-07. All rendered content and interactions are local reconstructions. Fixture titles distinguish observed structure from invented states. No provider requests or writes occur. Runtime verification covers fictional local fixtures only.',
    runtimeVerified: true,
    fixtures: [{"id": "default", "title": "OBSERVED structure: wide preview", "props": {"kind": "viewport", "initialState": "default"}}, {"id": "narrow", "title": "OBSERVED structure: 390px width", "props": {"kind": "viewport", "initialState": "narrow"}}, {"id": "disabled", "title": "RECONSTRUCTION: disabled fields", "props": {"kind": "viewport", "initialState": "disabled", "disabled": true}}],
    config: { viewports: [{ id: 'desktop', label: 'Desktop', width: 760 }, { id: 'narrow', label: 'Narrow', width: 390 }], toggles: [{ id: 'disabled', label: 'Interaction', onLabel: 'Disabled', offLabel: 'Enabled' }] },
    propsSchema: [{ name: 'kind', type: 'FramerKind', required: true, description: 'Selects an individual primary control.' }, { name: 'initialState', type: 'string', required: false, description: 'Initial fixture state. Unobserved states are labelled reconstruction.' }, { name: 'disabled', type: 'boolean', required: false, description: 'Disables local controls.' }],
  },
};
