export const mondayLeafFixtures = {
  'my-work-table': {
    title: 'My Work Table',
    category: 'My Work > Table',
    route: '/my_work',
    components: [
      'Table and Calendar tabs',
      'New item action',
      'text filter',
      'date-view control',
      'time-bucket groups',
    ],
    boundary: 'No item was created or changed.',
    ai: false,
  },
  'my-work-calendar': {
    title: 'My Work Calendar',
    category: 'My Work > Calendar',
    route: '/my_work',
    components: ['month navigation', 'calendar grid', 'task event', 'Table and Calendar tabs'],
    boundary: 'No date or item was changed.',
    ai: false,
  },
  'my-work-customize': {
    title: 'My Work Customize Drawer',
    category: 'My Work > Customize',
    route: '/my_work',
    components: [
      'General, Table and Calendar tabs',
      'People and Boards selectors',
      'Status, Date and Priority columns',
      'Hide done switch',
    ],
    boundary: 'No preference was changed or saved.',
    ai: false,
  },
  'template-center': {
    title: 'Template Center',
    category: 'Templates > Discovery',
    route: '/template_center',
    components: [
      'search field',
      'filter control',
      'category navigation',
      'creator filters',
      'template cards',
      'AI-powered category',
    ],
    boundary: 'No template was installed.',
    ai: true,
  },
  'docs-hub-ai-draft': {
    title: 'Docs Hub AI Draft',
    category: 'Docs > AI drafting',
    route: '/product_view/monday_documents/docs-hub',
    components: ['Create new doc', 'AI draft call to action', 'document template cards'],
    boundary: 'No document or AI draft was created.',
    ai: true,
  },
  'autopilot-health': {
    title: 'Autopilot Health',
    category: 'Autopilot > Health',
    route: 'modal from product navigation',
    components: [
      'filters',
      'success rate',
      'Critical, Major and Minor severity',
      'board suggestions',
    ],
    boundary: 'No suggestion was applied.',
    ai: true,
  },
  'autopilot-usage': {
    title: 'Autopilot Usage',
    category: 'Autopilot > Usage',
    route: 'modal from product navigation',
    components: [
      'billing-cycle selector',
      'automation and integration totals',
      'daily action graph',
      'top boards, creators and workflows',
      'workflow table',
      'connections table',
    ],
    boundary: 'No connection or automation was changed.',
    ai: true,
  },
  'sidekick-chat': {
    title: 'Sidekick Chat',
    category: 'AI Assistance > Sidekick',
    route: 'Sidekick panel',
    components: [
      'chat history',
      'new chat',
      'quick prompts',
      'composer',
      'connect tools',
      'context, files, skills and voice controls',
      'accuracy warning',
    ],
    boundary: 'No prompt, file or message was submitted.',
    ai: true,
  },
  'sidekick-scheduled-tasks': {
    title: 'Sidekick Scheduled Tasks',
    category: 'AI Assistance > Scheduled tasks',
    route: 'Sidekick panel',
    components: [
      'Morning brief',
      'Meeting Prep',
      'What is Urgent Today',
      'Meeting Action Items',
      'scheduled-task cards',
    ],
    boundary: 'No task or schedule was activated.',
    ai: true,
  },
  'sidekick-personalization': {
    title: 'Sidekick Personalization',
    category: 'AI Assistance > Personalization',
    route: 'Sidekick panel',
    components: [
      'import from other AI',
      'profile fields',
      'Telegram and WhatsApp connections',
      'custom guidelines',
      'suggestion chips',
    ],
    boundary: 'No profile, connection or guideline was saved.',
    ai: true,
  },
  'sidekick-skills': {
    title: 'Sidekick Skills',
    category: 'AI Assistance > Skills',
    route: 'Sidekick panel',
    components: [
      'skill inventory',
      'essential labels',
      'feature toggles',
      'project, content, meeting, research, enrichment and brand skills',
    ],
    boundary: 'No skill was enabled or disabled.',
    ai: true,
  },
  'agent-management-table': {
    title: 'Agent Management Table',
    category: 'AI Agents > My agents',
    route: '/ai_agents',
    components: [
      'empty-state management table',
      'Status, Members, Sharing, Tools, Activity and Credits columns',
    ],
    boundary: 'No agent was created or changed.',
    ai: true,
  },
  'agent-card': {
    title: 'Agent Directory Card',
    category: 'AI Agents > Directory',
    route: '/ai_agents',
    components: [
      'agent avatar',
      'role title',
      'capability summary',
      'install count',
      'Get agent action',
    ],
    boundary: 'No agent was installed.',
    ai: true,
  },
  'agent-model-selector': {
    title: 'Agent Model Selector',
    category: 'AI Agents > Model choice',
    route: '/ai_agents/new',
    components: ['Auto selection', 'Model option', 'Deep thinking option', 'checked state'],
    boundary: 'No model selection was persisted.',
    ai: true,
  },
  'vibe-app-launcher': {
    title: 'Vibe App Launcher',
    category: 'Vibe > All apps',
    route: '/monday_vibe',
    components: ['app search', 'My apps section', 'community section', 'new app action'],
    boundary: 'No app was created or opened for editing.',
    ai: true,
  },
  'vibe-template-gallery': {
    title: 'Vibe Template Gallery',
    category: 'Vibe > Templates',
    route: '/monday_vibe',
    components: ['category chips', 'search', 'sort', 'template cards', 'AI template labels'],
    boundary: 'No template was used.',
    ai: true,
  },
  'vibe-plan-gate': {
    title: 'Vibe Plan Gate',
    category: 'Vibe > Upgrade',
    route: 'dialog from /monday_vibe',
    components: [
      'Draft, Starter, Growth and Custom plan cards',
      'monthly prices',
      'published app and board limits',
      'AI credit note',
      'FAQ',
    ],
    boundary: 'No purchase or plan change was made.',
    ai: true,
  },
  'workflow-template-gallery': {
    title: 'Workflow Template Gallery',
    category: 'Workflows > Templates',
    route: '/ai_workflows',
    components: [
      'prompt-to-workflow composer',
      'Build workflow control',
      'Start from scratch',
      'category chips',
      'template cards',
    ],
    boundary: 'No prompt was submitted or workflow built.',
    ai: true,
  },
  'workflow-inventory': {
    title: 'Workflow Inventory',
    category: 'Workflows > All workflows',
    route: '/ai_workflows',
    components: ['active-limit meter', 'total count', 'workspace filter', 'empty table state'],
    boundary: 'No workflow was activated or published.',
    ai: true,
  },
  'notetaker-meeting-history': {
    title: 'Notetaker Meeting History',
    category: 'Notetaker > Meetings',
    route: '/product_view/notetaker/meetings-page-product-view',
    components: [
      'calendar sidebar',
      'Google and Outlook connection buttons',
      'meeting-history tabs',
      'demo meeting',
      'Add agent and Add Notetaker actions',
    ],
    boundary: 'No calendar was connected and no meeting was recorded.',
    ai: true,
  },
  'notetaker-filter-controls': {
    title: 'Notetaker Filter Controls',
    category: 'Notetaker > Filters',
    route: '/product_view/notetaker/meetings-page-product-view',
    components: [
      'participant search popover',
      'date calendar grid',
      'My meetings and Shared with me tabs',
    ],
    boundary: 'No filter was saved and no participant data was retained.',
    ai: true,
  },
  'workspace-content-table': {
    title: 'Workspace Content Table',
    category: 'Workspace > Content',
    route: 'workspace overview',
    components: ['content table', 'type and owner columns', 'AI summary column', 'row actions'],
    boundary: 'No workspace content was changed.',
    ai: true,
  },
  'workspace-collaborators': {
    title: 'Workspace Collaborators',
    category: 'Workspace > Collaborators',
    route: 'workspace overview',
    components: ['Agents table', 'Users table', 'role and access columns', 'agent promotion modal'],
    boundary: 'No member or agent was invited or changed.',
    ai: true,
  },
  'favorites-panel': {
    title: 'Favorites Panel',
    category: 'Navigation > Favorites',
    route: 'favorites panel',
    components: ['empty favorites state', 'recently viewed items', 'navigation controls'],
    boundary: 'No favorite was added or removed.',
    ai: false,
  },
  'notification-center': {
    title: 'Notification Center',
    category: 'Global utility > Notifications',
    route: 'notification panel',
    components: [
      'All, Mentioned and Assigned tabs',
      'search',
      'unread-only switch',
      'Microsoft Teams connection banner',
    ],
    boundary: 'No notification was marked or dismissed.',
    ai: false,
  },
  'update-feed': {
    title: 'Update Feed',
    category: 'Global utility > Updates',
    route: 'update feed',
    components: [
      'profile checklist',
      'board filters',
      'All updates, Mentioned, Bookmarked, All account and Scheduled tabs',
      'unread controls',
      'update card',
    ],
    boundary: 'No update state or profile checklist was changed.',
    ai: false,
  },
  'help-menu': {
    title: 'Help Menu',
    category: 'Global utility > Help',
    route: 'global popover',
    components: [
      'Contact support',
      'support history',
      'expert help',
      'Explore and learn',
      'What is new',
      'getting-started links',
    ],
    boundary: 'No support request was started.',
    ai: false,
  },
  'products-switcher': {
    title: 'Products Switcher',
    category: 'Global utility > Products',
    route: 'global popover',
    components: [
      'Work OS',
      'Explore',
      'Marketplace',
      'Workflows',
      'Template Center',
      'CRM trial',
      'Admin and Teams',
    ],
    boundary: 'No product trial or external route was activated.',
    ai: true,
  },
  'user-menu': {
    title: 'User Menu',
    category: 'Global utility > Account',
    route: 'global popover',
    components: [
      'Profile',
      'Import Data',
      'Developers',
      'Trash',
      'Archive',
      'Administration',
      'Teams',
      'Marketplace',
      'Labs',
      'theme and status controls',
    ],
    boundary: 'No account preference, status or session was changed.',
    ai: false,
  },
  'import-data': {
    title: 'Import Data Modal',
    category: 'Account utility > Import',
    route: 'modal from user menu',
    components: [
      'Excel',
      'Google Sheets',
      'Trello',
      'Asana',
      'Basecamp',
      'Meta Ads',
      'Zendesk',
      'Jira cloud and server sources',
    ],
    boundary: 'No source was connected and no data was imported.',
    ai: false,
  },
  'trash-archive': {
    title: 'Trash and Archive Tables',
    category: 'Account utility > Retention',
    route: 'account utility screens',
    components: ['item tables', 'filters', 'month and year controls', 'empty states'],
    boundary: 'No item was restored or deleted.',
    ai: false,
  },
  'teams-management': {
    title: 'Teams Management',
    category: 'Account utility > Teams',
    route: 'teams modal',
    components: ['search', 'filter', 'teams table', 'empty state', 'create-team boundary'],
    boundary: 'No team or membership was changed.',
    ai: false,
  },
  'admin-navigation': {
    title: 'Administration Navigation',
    category: 'Administration > Index',
    route: '/admin/general/profile',
    components: [
      'General',
      'Customization',
      'Directory',
      'Security',
      'AI governance',
      'Connections',
      'Billing',
      'Usage stats',
      'Tidy up',
      'Content directory',
      'Apps',
      'Mobile apps',
      'Permissions',
      'Cross-account copier',
    ],
    boundary: 'No administrative setting was changed.',
    ai: true,
  },
  'ai-permissions': {
    title: 'AI Permissions',
    category: 'Administration > AI governance',
    route: '/admin/ai',
    components: [
      'feature permission rows',
      'monday agents, Service AI, CRM Leads, AI Connectors, external agents, AI Blocks, Sidekick, API access, Vibe and Notetaker',
      'role selector',
      'Enterprise entitlement gate',
    ],
    boundary: 'No permission or role was changed.',
    ai: true,
  },
  'ai-credit-usage': {
    title: 'AI Credit Usage',
    category: 'Administration > AI governance',
    route: '/admin/ai',
    components: [
      'credit meter',
      'billing period',
      'Extract info, Categorize, Summarize and Translate examples',
    ],
    boundary:
      'Credit display was observed only. The later AI suggestion preview may affect provider usage and was not treated as a write.',
    ai: true,
  },
  'ai-usage-limits': {
    title: 'AI Usage Limits',
    category: 'Administration > AI governance',
    route: '/admin/ai',
    components: [
      'hard and soft limit controls',
      'user agents',
      'AI workflows',
      'AI columns and automations',
      'connectors',
      'third-party agents',
      'personal API',
      'Vibe',
      'Notetaker',
      'Sidekick',
    ],
    boundary: 'No usage limit was changed.',
    ai: true,
  },
  'ai-agent-governance': {
    title: 'AI Agent Governance',
    category: 'Administration > AI governance',
    route: '/admin/ai',
    components: [
      'All Agents table',
      'privacy risk',
      'model',
      'credits',
      'access columns',
      'empty state',
    ],
    boundary: 'No agent policy or access was changed.',
    ai: true,
  },
  'ai-account-settings': {
    title: 'AI Account Settings',
    category: 'Administration > AI governance',
    route: '/admin/ai',
    components: [
      'Enable monday AI',
      'background optimizations',
      'WhatsApp',
      'Telegram',
      'enforcement banners',
      'enabled switches',
    ],
    boundary: 'No setting was toggled.',
    ai: true,
  },
  'board-options-menu': {
    title: 'Board Options Menu',
    category: 'Board > Options',
    route: 'existing board',
    components: [
      'Power-Ups',
      'AI suggestions',
      'Convert to project',
      'Activity',
      'Discussion',
      'Notifications',
      'Permissions',
      'Settings',
      'More',
      'Archive, delete and trash actions',
    ],
    boundary: 'No board setting or lifecycle action was executed.',
    ai: true,
  },
  'group-actions-menu': {
    title: 'Group Actions Menu',
    category: 'Board > Group actions',
    route: 'existing board',
    components: [
      'collapse',
      'select',
      'add',
      'duplicate',
      'move',
      'rename',
      'color',
      'export',
      'apps',
      'delete and archive',
    ],
    boundary: 'No group action was executed.',
    ai: false,
  },
  'item-actions-menu': {
    title: 'Item Actions Menu',
    category: 'Board > Item actions',
    route: 'existing board',
    components: [
      'open',
      'new tab',
      'copy',
      'move',
      'duplicate',
      'create below',
      'subitem',
      'convert',
      'apps',
      'archive and delete',
    ],
    boundary: 'No item action was executed.',
    ai: false,
  },
  'column-actions-menu': {
    title: 'Column Actions Menu',
    category: 'Board > Column actions',
    route: 'existing board',
    components: [
      'settings',
      'AI-powered actions',
      'Auto-assign labels',
      'Set a custom prompt',
      'filter',
      'sort',
      'collapse',
      'group',
      'duplicate',
      'add',
      'change',
      'save',
      'rename and delete',
    ],
    boundary: 'No column, label or prompt action was executed.',
    ai: true,
  },
  'add-column-menu': {
    title: 'Add Column Menu',
    category: 'Board > Add column',
    route: 'existing board',
    components: [
      'search',
      'describe a column',
      'essential types',
      'super-useful types',
      'Extract info',
      'More columns',
    ],
    boundary: 'No column was added.',
    ai: false,
  },
  'automation-center': {
    title: 'Automation Center',
    category: 'Board > Automate',
    route: 'existing board',
    components: [
      'category navigation',
      'integration recipes',
      'Create from scratch',
      'create with AI entry',
    ],
    boundary: 'No automation or prompt was created.',
    ai: true,
  },
  'ai-automation-templates': {
    title: 'AI Automation Templates',
    category: 'Board > Automate > AI',
    route: 'existing board',
    components: [
      'fill column from item, update, subitem, name, column and email activity',
      'sentiment analysis recipes',
    ],
    boundary: 'No recipe was installed or run.',
    ai: true,
  },
  'board-integrations': {
    title: 'Board Integrations',
    category: 'Board > Integrate',
    route: 'existing board',
    components: [
      'integration count',
      'recommended CRM automations',
      'ZoomInfo',
      'AI Sales Agent',
      'QuickBooks Installed badge',
    ],
    boundary: 'No integration was connected, configured or run.',
    ai: true,
  },
  'board-view-menu': {
    title: 'Board View Menu',
    category: 'Board > Add view',
    route: 'existing board',
    components: [
      'Table',
      'Gantt',
      'Chart',
      'Calendar',
      'Kanban',
      'Doc',
      'File gallery',
      'Form',
      'Dashboard',
      'Build with Vibe',
      'Apps',
      'Explore more',
    ],
    boundary: 'No view or app was added.',
    ai: true,
  },
  'ai-suggestions-preview': {
    title: 'AI Suggestions Preview',
    category: 'Board > Options > AI suggestions',
    route: 'existing board',
    components: [
      'generated suggestion preview',
      'Add column action',
      'Cancel action',
      'Give feedback action',
    ],
    boundary:
      'Provider computation ran automatically after opening the entry. The preview was canceled and no column was added or board data saved.',
    ai: true,
  },
  'navigation-bar-customization': {
    title: 'Navigation Bar Customization',
    category: 'Navigation > Customize menu',
    route: 'modal from More tools',
    components: [
      'fixed product rail items',
      'optional navigation checkboxes',
      'Save changes and Cancel actions',
    ],
    boundary: 'No navigation preference was changed or saved.',
    ai: true,
  },
  'workspace-options-menu': {
    title: 'Workspace Options Menu',
    category: 'Workspace > Options',
    route: 'workspace overview',
    components: ['Rename workspace', 'Change type submenu', 'Leave workspace', 'Delete workspace'],
    boundary: 'No workspace action was executed.',
    ai: false,
  },
  'keyboard-shortcuts': {
    title: 'Keyboard Shortcuts',
    category: 'Account utility > Shortcuts',
    route: 'modal from user menu',
    components: [
      'System and Board sections',
      'search, dialog and navigation shortcuts',
      'board editing and selection shortcuts',
      'group, column, activity and sorting shortcuts',
    ],
    boundary: 'No shortcut was executed.',
    ai: false,
  },
  'theme-selector': {
    title: 'Theme Selector',
    category: 'Account utility > Theme',
    route: 'submenu from user menu',
    components: ['Light', 'Dark', 'Night', 'System default'],
    boundary: 'No theme was selected or saved.',
    ai: false,
  },
  'developer-center': {
    title: 'Developer Center',
    category: 'Developer tools > Overview',
    route: '/apps/manage',
    components: [
      'My apps',
      'API playground',
      'API analytics',
      'app creation call to action',
      'documentation, MCP server, community and security resources',
    ],
    boundary: 'No app was created and the API token screen was not opened.',
    ai: false,
  },
  'app-marketplace': {
    title: 'App Marketplace',
    category: 'Marketplace > Apps',
    route: '/marketplace/v2/app',
    components: [
      'Apps and AI hub tabs',
      'search and category navigation',
      'featured, trending, editor choice and new sections',
      'app, AI team member and connector cards',
    ],
    boundary: 'No app or connector was installed.',
    ai: true,
  },
  'marketplace-ai-hub': {
    title: 'Marketplace AI Hub',
    category: 'Marketplace > AI hub',
    route: '/marketplace/v2/app/agents',
    components: [
      'Discover, Agents, AI connectors, Agent skills and Sidekick tools tabs',
      'agent cards',
      'AI connector cards',
      'skill inventory',
      'Sidekick tool inventory',
    ],
    boundary: 'No agent, skill, connector or tool was installed or activated.',
    ai: true,
  },
  'marketplace-installed-apps': {
    title: 'Marketplace Installed Apps',
    category: 'Marketplace > Manage',
    route: '/marketplace/v2/app/installed',
    components: [
      'Installed and Pending installs tabs',
      'search and type filter',
      'installed-app table',
      'status and plan columns',
    ],
    boundary: 'No app was installed, disabled or removed.',
    ai: false,
  },
  'monday-labs': {
    title: 'monday.labs Experiments',
    category: 'Account utility > monday.labs',
    route: 'modal from user menu',
    components: [
      'search and sort',
      'Alpha, Beta, Internal, Gradual release and Development labels',
      'experimental feature cards',
      'feature toggles',
    ],
    boundary: 'No experiment was enabled or disabled.',
    ai: false,
  },
  'spaces-alpha': {
    title: 'Spaces Alpha',
    category: 'Account utility > Spaces',
    route: '/spaces',
    components: [
      'My spaces and My public profile tabs',
      'community introduction',
      'video banner',
      'Create new space empty state',
    ],
    boundary: 'No space or public profile was created.',
    ai: false,
  },
  'profile-navigation': {
    title: 'Profile Settings Navigation',
    category: 'Profile > Personal info',
    route: 'profile settings',
    components: [
      'Personal info',
      'Schedule',
      'Working status',
      'Notifications',
      'Language and region',
      'Password',
      'Session history',
    ],
    boundary: 'No profile field was changed. Password and session history screens were not opened.',
    ai: false,
  },
  'profile-schedule': {
    title: 'Profile Schedule',
    category: 'Profile > Schedule',
    route: 'profile settings schedule route',
    components: ['Schedule heading', 'account-specific empty content state'],
    boundary: 'No schedule was changed.',
    ai: false,
  },
  'profile-working-status': {
    title: 'Working Status Selector',
    category: 'Profile > Working status',
    route: 'profile settings',
    components: [
      'In office',
      'Working from home',
      'Out sick',
      'On break',
      'Out of office',
      'Working outside',
      'Family time',
      'Do not disturb',
      'date and notification controls',
    ],
    boundary: 'No status, date or notification setting was changed.',
    ai: false,
  },
  'profile-notifications': {
    title: 'Profile Notifications',
    category: 'Profile > Notifications',
    route: 'profile settings',
    components: [
      'Notifications heading',
      'important-notifications disclosure',
      'notification preference surface',
    ],
    boundary: 'No notification preference was changed.',
    ai: false,
  },
  'profile-language-region': {
    title: 'Language and Region Settings',
    category: 'Profile > Language and region',
    route: 'profile settings',
    components: [
      'language selector',
      'timezone selector',
      '12 and 24 hour controls',
      'date format',
      'first day of week',
    ],
    boundary:
      'No language, timezone or locale setting was changed. Provider values were not retained.',
    ai: false,
  },
  'mobile-app-promotion': {
    title: 'Mobile App Promotion',
    category: 'Account utility > Mobile app',
    route: 'modal from user menu',
    components: [
      'monday mobile app call to action',
      'monday agents mobile app call to action',
      'product illustrations',
    ],
    boundary: 'No app store link or installation flow was opened.',
    ai: true,
  },
  'account-plan-comparison': {
    title: 'Account Plan Comparison',
    category: 'Account > Plans',
    route: '/pricing_page/p1',
    components: [
      'Basic, Standard, Pro and Enterprise cards',
      'seat and billing-period controls',
      'feature comparison',
      'AI essentials, Premium AI and Enterprise AI sections',
      'FAQ',
    ],
    boundary: 'No plan, billing period, seat count or purchase was changed.',
    ai: true,
  },
  'ai-plan-consultant': {
    title: 'AI Plan Consultant',
    category: 'Account > Plans > AI consultant',
    route: 'overlay on plan comparison',
    components: [
      'AI consultant message',
      'Show recommended plan action',
      'recommendation boundary',
    ],
    boundary: 'No recommendation was generated and no purchase flow was started.',
    ai: true,
  },
  'admin-account-profile': {
    title: 'Admin Account Profile',
    category: 'Administration > General > Profile',
    route: '/admin/general/profile',
    components: ['account name and URL fields', 'data-region display', 'Save changes action'],
    boundary: 'No account profile value was changed or saved. Provider identity was not retained.',
    ai: false,
  },
  'admin-account-settings': {
    title: 'Admin Account Settings',
    category: 'Administration > General > Account',
    route: '/admin/general/account',
    components: [
      'weekend controls',
      'account home-page selector',
      'dashboard and Vibe options',
      'account export action',
      'exclude attachments checkbox',
    ],
    boundary: 'No setting was saved and no account data was exported.',
    ai: true,
  },
  'admin-work-schedules': {
    title: 'Admin Work Schedules',
    category: 'Administration > General > Work schedule',
    route: '/admin/general/work-schedule',
    components: [
      'Individual and Team schedules tabs',
      'search and team filter',
      'resource schedule table',
      'work schedule and time-off columns',
      'trial feature notice',
    ],
    boundary: 'No schedule, assignment or time-off record was changed.',
    ai: false,
  },
  'admin-branding': {
    title: 'Admin Branding',
    category: 'Administration > Customization > Branding',
    route: '/admin/customization/branding',
    components: ['main-menu logo', 'email-header logo', 'image recommendations', 'Change actions'],
    boundary: 'No logo was uploaded or changed.',
    ai: true,
  },
  'admin-feature-controls': {
    title: 'Admin Feature Controls',
    category: 'Administration > Customization > Features',
    route: '/admin/customization/features',
    components: [
      'GIF, link and file preview toggles',
      'due-date reminder and status update controls',
      'online activity and mobile controls',
      'custom email, Spaces and form controls',
    ],
    boundary: 'No feature control was toggled.',
    ai: true,
  },
  'admin-board-defaults': {
    title: 'Admin Board Defaults',
    category: 'Administration > Customization > Boards',
    route: '/admin/customization/boards',
    components: ['default status label rows', 'drag handles', 'Save changes action'],
    boundary: 'No label was reordered or saved.',
    ai: false,
  },
  'admin-user-profile-fields': {
    title: 'Admin User Profile Fields',
    category: 'Administration > Customization > User profile',
    route: '/admin/customization/user-profile',
    components: ['required profile-field list', 'Add field action', 'row action menus'],
    boundary: 'No field was added, removed or changed.',
    ai: false,
  },
  'admin-user-notification-defaults': {
    title: 'Admin User Notification Defaults',
    category: 'Administration > Customization > User notifications',
    route: '/admin/customization/user-notifications',
    components: [
      'existing-user boundary',
      'email notification disclosure',
      'Microsoft Teams connection',
      'Slack connection',
    ],
    boundary: 'No default was changed and no external service was connected.',
    ai: true,
  },
  'admin-users-table': {
    title: 'Admin Users Table',
    category: 'Administration > Directory > Users',
    route: '/admin/my-team/my-team',
    components: [
      'search',
      'filters and options',
      'user-management table',
      'role and status columns',
    ],
    boundary: 'No user, role or status was changed. Provider identity was not retained.',
    ai: false,
  },
  'admin-invitations': {
    title: 'Admin Invitations',
    category: 'Administration > Directory > Invitations',
    route: '/admin/my-team/invitations',
    components: [
      'Pending approval and Sent invitations tabs',
      'Google Workspace invite',
      'Invite action',
      'Email, Role, Requested by, Date, Products and Actions columns',
    ],
    boundary: 'No invitation was sent or approved.',
    ai: true,
  },
  'admin-departments': {
    title: 'Admin Departments',
    category: 'Administration > Directory > Departments',
    route: '/admin/my-team/departments',
    components: [
      'Export CSV and Add Department actions',
      'Enterprise plan gate',
      'reserved, assigned and available seat columns',
      'row menus',
    ],
    boundary: 'No department was added or exported.',
    ai: true,
  },
  'admin-board-ownership': {
    title: 'Admin Board Ownership',
    category: 'Administration > Directory > Board ownership',
    route: '/admin/my-team/board-ownership',
    components: [
      'current-owner search',
      'new-owner search',
      'Add new owner action',
      'boards-without-owners section',
    ],
    boundary: 'No board ownership was transferred.',
    ai: false,
  },
  'admin-automation-ownership': {
    title: 'Admin Automation Ownership',
    category: 'Administration > Directory > Automations ownership',
    route: '/admin/my-team/automations-ownership',
    components: [
      'current and new owner selectors',
      'transfer action',
      'default owner for deactivated users',
      'integration reactivation warning',
    ],
    boundary: 'No automation ownership or default owner was changed.',
    ai: false,
  },
  'admin-security-authentication': {
    title: 'Admin Security Authentication',
    category: 'Administration > Security > Authentication',
    route: '/admin/security/login',
    components: [
      'authentication policies',
      'SCIM, guest-domain and IP restriction gates',
      'default product selector',
      'two-factor authentication action',
      'remote support section',
    ],
    boundary: 'No authentication, support or security setting was changed.',
    ai: true,
  },
  'admin-security-audit': {
    title: 'Admin Security Audit',
    category: 'Administration > Security > Audit',
    route: '/admin/security/audit',
    components: ['Enterprise plan gate', 'upgrade call to action'],
    boundary: 'No upgrade or audit export was started.',
    ai: false,
  },
  'admin-security-compliance': {
    title: 'Admin Security Compliance',
    category: 'Administration > Security > Compliance',
    route: '/admin/security/compliance',
    components: [
      'HIPAA compliance gate',
      'Unlock HIPAA Compliance action',
      'Business Associate Agreement checkbox',
      'disabled compliance switch',
    ],
    boundary: 'No compliance setting or agreement was accepted.',
    ai: false,
  },
  'admin-security-advanced': {
    title: 'Admin Advanced Security',
    category: 'Administration > Security > Advanced',
    route: '/admin/security/advanced',
    components: ['Enterprise plan gate', 'upgrade link'],
    boundary: 'No security setting or upgrade was started.',
    ai: false,
  },
  'admin-claim-domain': {
    title: 'Admin Claim Domain',
    category: 'Administration > Security > Claim domain',
    route: '/admin/security/domains',
    components: [
      'Claim a domain action',
      'domain verification table',
      'DNS and Manual methods',
      'verified and waiting states',
      'account-creation radio controls',
    ],
    boundary: 'No domain was claimed and no account-creation rule was changed.',
    ai: true,
  },
  'admin-automation-connections': {
    title: 'Admin Automation Connections',
    category: 'Administration > Connections > Automation connections',
    route: '/admin/integrations/connections',
    components: [
      'search and filter controls',
      'connection table',
      'no-connections empty state',
      'Explore integrations action',
    ],
    boundary: 'No integration was explored, connected or changed.',
    ai: false,
  },
  'admin-on-premise-profiles': {
    title: 'Admin On-Premise Profiles',
    category: 'Administration > Connections > On-premise profiles',
    route: '/admin/integrations/on-prem-profiles',
    components: [
      'profiles table',
      'New profile action',
      'shared configuration empty state',
      'safety explanation',
    ],
    boundary: 'No connection profile or secret was created or viewed.',
    ai: false,
  },
  'admin-billing-overview': {
    title: 'Admin Billing Overview',
    category: 'Administration > Billing > Overview',
    route: '/admin/billing/overview',
    components: [
      'product and plan summary',
      'seat and member counts',
      'trial notice',
      'Upgrade now',
      'billing help',
      'Close account boundary',
    ],
    boundary: 'No upgrade, support request or account closure was started.',
    ai: false,
  },
  'admin-invoice-settings': {
    title: 'Admin Invoice Settings',
    category: 'Administration > Billing > Settings',
    route: '/admin/billing/settings',
    components: [
      'Invoice settings heading',
      'upcoming-invoice notice',
      'billing-details form boundary',
    ],
    boundary: 'No billing detail was read into the catalogue or changed.',
    ai: true,
  },
  'admin-invoices': {
    title: 'Admin Invoices',
    category: 'Administration > Billing > Invoices',
    route: '/admin/billing/invoices',
    components: [
      'Date, Payment method, Amount, Type, Status and Actions columns',
      'empty invoice state',
    ],
    boundary: 'No invoice or payment detail was opened or downloaded.',
    ai: false,
  },
  'admin-basic-usage': {
    title: 'Admin Basic Usage Stats',
    category: 'Administration > Usage stats > Basic',
    route: '/admin/stats/basic',
    components: [
      '60-day summary',
      'boards updated, people posted and updates metrics',
      'storage used',
      'people activity',
      'boards created breakdown',
    ],
    boundary: 'Usage values were observed only and provider identities were not retained.',
    ai: false,
  },
  'admin-storage-usage': {
    title: 'Admin Storage Usage',
    category: 'Administration > Usage stats > Storage',
    route: '/admin/stats/storage',
    components: ['storage-used meter', 'file type and capacity table'],
    boundary: 'No file or storage setting was changed.',
    ai: false,
  },
  'admin-automation-usage': {
    title: 'Admin Automation Usage',
    category: 'Administration > Usage stats > Automations',
    route: '/admin/stats/automations',
    components: [
      'action usage',
      'daily graph',
      'top boards, creators and automations',
      'CSV export actions',
      'automation table',
    ],
    boundary: 'No report was exported and no automation was changed.',
    ai: true,
  },
  'admin-integration-usage': {
    title: 'Admin Integration Usage',
    category: 'Administration > Usage stats > Integrations',
    route: '/admin/stats/integrations',
    components: ['date-range selector', 'usage chart or empty state', 'monthly activity message'],
    boundary: 'No integration or date range was changed.',
    ai: false,
  },
  'admin-advanced-usage': {
    title: 'Admin Advanced Usage',
    category: 'Administration > Usage stats > Advanced',
    route: '/admin/stats/advanced',
    components: [
      'trending boards table',
      'top creators table',
      'top communicators table',
      'weekly columns',
    ],
    boundary: 'Provider names and activity values were not retained or changed.',
    ai: false,
  },
  'admin-tidy-up': {
    title: 'Admin Tidy Up',
    category: 'Administration > Tidy up',
    route: '/admin/shredder/shredder',
    components: [
      'Boards and Archived boards tabs',
      'Creator, Last updated and Created columns',
      'organization guidance',
    ],
    boundary: 'No board was archived, restored or deleted.',
    ai: false,
  },
  'admin-content-directory': {
    title: 'Admin Content Directory',
    category: 'Administration > Content directory',
    route: '/admin/contentManagement/all',
    components: [
      'search and account-wide content description',
      'Export all action',
      'additional actions menu',
      'Enterprise plan gate',
    ],
    boundary: 'No content was searched, exported or changed.',
    ai: false,
  },
  'admin-mobile-experiences': {
    title: 'Admin Mobile Experiences',
    category: 'Administration > Mobile apps',
    route: '/admin/mobileAdmin/manage',
    components: [
      'Create mobile experience action',
      'experience search',
      'Vibe app status',
      'connected boards and assigned users columns',
      'trial notice',
    ],
    boundary: 'No mobile experience was created or assigned.',
    ai: true,
  },
  'admin-permissions-matrix': {
    title: 'Admin Permissions Matrix',
    category: 'Administration > Permissions',
    route: '/admin/permissions/permissions',
    components: [
      'Admin, Member, Viewer and Guest role selector',
      'AI Management, AI Features and Agents sections',
      'account, board, docs, user, workflow and communication permissions',
      'Admin Privileges, Resource Management and Templates sections',
      'Enterprise plan gate',
    ],
    boundary: 'No role or permission was changed.',
    ai: true,
  },
  'admin-cross-account-copier': {
    title: 'Admin Cross-Account Copier',
    category: 'Administration > Cross account copier',
    route: '/admin/cross-account/duplicate',
    components: [
      'folder selector',
      'current and destination account fields',
      'eligibility guidance',
      'Continue action',
    ],
    boundary: 'No destination was entered and no content was copied.',
    ai: false,
  },
  'admin-apps-menu': {
    title: 'Admin Apps Menu',
    category: 'Administration > Admin apps',
    route: 'admin navigation popover',
    components: ['Installed section', 'No installed apps state', 'Explore app marketplace action'],
    boundary: 'No app marketplace route or installation flow was opened from the menu.',
    ai: false,
  },
} as const;

export type MondayLeafVariant = keyof typeof mondayLeafFixtures;

export const mondayLeafEntries = Object.entries(mondayLeafFixtures).map(([variant, fixture]) => ({
  id: `monday-${variant}`,
  variant: variant as MondayLeafVariant,
  description: fixture.title,
}));
