export const mondayLeafFixtures = {
  'my-work-table': {
    title: 'My Work Table',
    category: 'My Work > Table',
    route: '/my_work',
    components: [
      'Table and Calendar tabs',
      'New item action',
      'text filter',
      'date-view control',
      'time-bucket groups',
    ],
    boundary: 'No item was created or changed.',
    ai: false,
  },
  'my-work-calendar': {
    title: 'My Work Calendar',
    category: 'My Work > Calendar',
    route: '/my_work',
    components: ['month navigation', 'calendar grid', 'task event', 'Table and Calendar tabs'],
    boundary: 'No date or item was changed.',
    ai: false,
  },
  'my-work-customize': {
    title: 'My Work Customize Drawer',
    category: 'My Work > Customize',
    route: '/my_work',
    components: [
      'General, Table and Calendar tabs',
      'People and Boards selectors',
      'Status, Date and Priority columns',
      'Hide done switch',
    ],
    boundary: 'No preference was changed or saved.',
    ai: false,
  },
  'template-center': {
    title: 'Template Center',
    category: 'Templates > Discovery',
    route: '/template_center',
    components: [
      'search field',
      'filter control',
      'category navigation',
      'creator filters',
      'template cards',
      'AI-powered category',
    ],
    boundary: 'No template was installed.',
    ai: false,
  },
  'docs-hub-ai-draft': {
    title: 'Docs Hub AI Draft',
    category: 'Docs > AI drafting',
    route: '/product_view/monday_documents/docs-hub',
    components: ['Create new doc', 'AI draft call to action', 'document template cards'],
    boundary: 'No document or AI draft was created.',
    ai: true,
  },
  'autopilot-health': {
    title: 'Autopilot Health',
    category: 'Autopilot > Health',
    route: 'modal from product navigation',
    components: [
      'filters',
      'success rate',
      'Critical, Major and Minor severity',
      'board suggestions',
    ],
    boundary: 'No suggestion was applied.',
    ai: true,
  },
  'autopilot-usage': {
    title: 'Autopilot Usage',
    category: 'Autopilot > Usage',
    route: 'modal from product navigation',
    components: [
      'billing-cycle selector',
      'automation and integration totals',
      'daily action graph',
      'top boards, creators and workflows',
      'workflow table',
      'connections table',
    ],
    boundary: 'No connection or automation was changed.',
    ai: true,
  },
  'sidekick-chat': {
    title: 'Sidekick Chat',
    category: 'AI Assistance > Sidekick',
    route: 'Sidekick panel',
    components: [
      'chat history',
      'new chat',
      'quick prompts',
      'composer',
      'connect tools',
      'context, files, skills and voice controls',
      'accuracy warning',
    ],
    boundary: 'No prompt, file or message was submitted.',
    ai: true,
  },
  'sidekick-scheduled-tasks': {
    title: 'Sidekick Scheduled Tasks',
    category: 'AI Assistance > Scheduled tasks',
    route: 'Sidekick panel',
    components: [
      'Morning brief',
      'Meeting Prep',
      'What is Urgent Today',
      'Meeting Action Items',
      'scheduled-task cards',
    ],
    boundary: 'No task or schedule was activated.',
    ai: true,
  },
  'sidekick-personalization': {
    title: 'Sidekick Personalization',
    category: 'AI Assistance > Personalization',
    route: 'Sidekick panel',
    components: [
      'import from other AI',
      'profile fields',
      'Telegram and WhatsApp connections',
      'custom guidelines',
      'suggestion chips',
    ],
    boundary: 'No profile, connection or guideline was saved.',
    ai: true,
  },
  'sidekick-skills': {
    title: 'Sidekick Skills',
    category: 'AI Assistance > Skills',
    route: 'Sidekick panel',
    components: [
      'skill inventory',
      'essential labels',
      'feature toggles',
      'project, content, meeting, research, enrichment and brand skills',
    ],
    boundary: 'No skill was enabled or disabled.',
    ai: true,
  },
  'agent-management-table': {
    title: 'Agent Management Table',
    category: 'AI Agents > My agents',
    route: '/ai_agents',
    components: [
      'empty-state management table',
      'Status, Members, Sharing, Tools, Activity and Credits columns',
    ],
    boundary: 'No agent was created or changed.',
    ai: true,
  },
  'agent-card': {
    title: 'Agent Directory Card',
    category: 'AI Agents > Directory',
    route: '/ai_agents',
    components: [
      'agent avatar',
      'role title',
      'capability summary',
      'install count',
      'Get agent action',
    ],
    boundary: 'No agent was installed.',
    ai: true,
  },
  'agent-model-selector': {
    title: 'Agent Model Selector',
    category: 'AI Agents > Model choice',
    route: '/ai_agents/new',
    components: ['Auto selection', 'Model option', 'Deep thinking option', 'checked state'],
    boundary: 'No model selection was persisted.',
    ai: true,
  },
  'vibe-app-launcher': {
    title: 'Vibe App Launcher',
    category: 'Vibe > All apps',
    route: '/monday_vibe',
    components: ['app search', 'My apps section', 'community section', 'new app action'],
    boundary: 'No app was created or opened for editing.',
    ai: true,
  },
  'vibe-template-gallery': {
    title: 'Vibe Template Gallery',
    category: 'Vibe > Templates',
    route: '/monday_vibe',
    components: ['category chips', 'search', 'sort', 'template cards', 'AI template labels'],
    boundary: 'No template was used.',
    ai: true,
  },
  'vibe-plan-gate': {
    title: 'Vibe Plan Gate',
    category: 'Vibe > Upgrade',
    route: 'dialog from /monday_vibe',
    components: [
      'Draft, Starter, Growth and Custom plan cards',
      'monthly prices',
      'published app and board limits',
      'AI credit note',
      'FAQ',
    ],
    boundary: 'No purchase or plan change was made.',
    ai: true,
  },
  'workflow-template-gallery': {
    title: 'Workflow Template Gallery',
    category: 'Workflows > Templates',
    route: '/ai_workflows',
    components: [
      'prompt-to-workflow composer',
      'Build workflow control',
      'Start from scratch',
      'category chips',
      'template cards',
    ],
    boundary: 'No prompt was submitted or workflow built.',
    ai: true,
  },
  'workflow-inventory': {
    title: 'Workflow Inventory',
    category: 'Workflows > All workflows',
    route: '/ai_workflows',
    components: ['active-limit meter', 'total count', 'workspace filter', 'empty table state'],
    boundary: 'No workflow was activated or published.',
    ai: true,
  },
  'notetaker-meeting-history': {
    title: 'Notetaker Meeting History',
    category: 'Notetaker > Meetings',
    route: '/product_view/notetaker/meetings-page-product-view',
    components: [
      'calendar sidebar',
      'Google and Outlook connection buttons',
      'meeting-history tabs',
      'demo meeting',
      'Add agent and Add Notetaker actions',
    ],
    boundary: 'No calendar was connected and no meeting was recorded.',
    ai: true,
  },
  'notetaker-filter-controls': {
    title: 'Notetaker Filter Controls',
    category: 'Notetaker > Filters',
    route: '/product_view/notetaker/meetings-page-product-view',
    components: [
      'participant search popover',
      'date calendar grid',
      'My meetings and Shared with me tabs',
    ],
    boundary: 'No filter was saved and no participant data was retained.',
    ai: true,
  },
  'workspace-content-table': {
    title: 'Workspace Content Table',
    category: 'Workspace > Content',
    route: 'workspace overview',
    components: ['content table', 'type and owner columns', 'AI summary column', 'row actions'],
    boundary: 'No workspace content was changed.',
    ai: false,
  },
  'workspace-collaborators': {
    title: 'Workspace Collaborators',
    category: 'Workspace > Collaborators',
    route: 'workspace overview',
    components: ['Agents table', 'Users table', 'role and access columns', 'agent promotion modal'],
    boundary: 'No member or agent was invited or changed.',
    ai: false,
  },
  'favorites-panel': {
    title: 'Favorites Panel',
    category: 'Navigation > Favorites',
    route: 'favorites panel',
    components: ['empty favorites state', 'recently viewed items', 'navigation controls'],
    boundary: 'No favorite was added or removed.',
    ai: false,
  },
  'notification-center': {
    title: 'Notification Center',
    category: 'Global utility > Notifications',
    route: 'notification panel',
    components: [
      'All, Mentioned and Assigned tabs',
      'search',
      'unread-only switch',
      'Microsoft Teams connection banner',
    ],
    boundary: 'No notification was marked or dismissed.',
    ai: false,
  },
  'update-feed': {
    title: 'Update Feed',
    category: 'Global utility > Updates',
    route: 'update feed',
    components: [
      'profile checklist',
      'board filters',
      'All updates, Mentioned, Bookmarked, All account and Scheduled tabs',
      'unread controls',
      'update card',
    ],
    boundary: 'No update state or profile checklist was changed.',
    ai: false,
  },
  'help-menu': {
    title: 'Help Menu',
    category: 'Global utility > Help',
    route: 'global popover',
    components: [
      'Contact support',
      'support history',
      'expert help',
      'Explore and learn',
      'What is new',
      'getting-started links',
    ],
    boundary: 'No support request was started.',
    ai: false,
  },
  'products-switcher': {
    title: 'Products Switcher',
    category: 'Global utility > Products',
    route: 'global popover',
    components: [
      'Work OS',
      'Explore',
      'Marketplace',
      'Workflows',
      'Template Center',
      'CRM trial',
      'Admin and Teams',
    ],
    boundary: 'No product trial or external route was activated.',
    ai: false,
  },
  'user-menu': {
    title: 'User Menu',
    category: 'Global utility > Account',
    route: 'global popover',
    components: [
      'Profile',
      'Import Data',
      'Developers',
      'Trash',
      'Archive',
      'Administration',
      'Teams',
      'Marketplace',
      'Labs',
      'theme and status controls',
    ],
    boundary: 'No account preference, status or session was changed.',
    ai: false,
  },
  'import-data': {
    title: 'Import Data Modal',
    category: 'Account utility > Import',
    route: 'modal from user menu',
    components: [
      'Excel',
      'Google Sheets',
      'Trello',
      'Asana',
      'Basecamp',
      'Meta Ads',
      'Zendesk',
      'Jira cloud and server sources',
    ],
    boundary: 'No source was connected and no data was imported.',
    ai: false,
  },
  'trash-archive': {
    title: 'Trash and Archive Tables',
    category: 'Account utility > Retention',
    route: 'account utility screens',
    components: ['item tables', 'filters', 'month and year controls', 'empty states'],
    boundary: 'No item was restored or deleted.',
    ai: false,
  },
  'teams-management': {
    title: 'Teams Management',
    category: 'Account utility > Teams',
    route: 'teams modal',
    components: ['search', 'filter', 'teams table', 'empty state', 'create-team boundary'],
    boundary: 'No team or membership was changed.',
    ai: false,
  },
  'admin-navigation': {
    title: 'Administration Navigation',
    category: 'Administration > Index',
    route: '/admin/general/profile',
    components: [
      'General',
      'Customization',
      'Directory',
      'Security',
      'AI governance',
      'Connections',
      'Billing',
      'Usage stats',
      'Tidy up',
      'Content directory',
      'Apps',
      'Mobile apps',
      'Permissions',
      'Cross-account copier',
    ],
    boundary: 'No administrative setting was changed.',
    ai: false,
  },
  'ai-permissions': {
    title: 'AI Permissions',
    category: 'Administration > AI governance',
    route: '/admin/ai',
    components: [
      'feature permission rows',
      'monday agents, Service AI, CRM Leads, AI Connectors, external agents, AI Blocks, Sidekick, API access, Vibe and Notetaker',
      'role selector',
      'Enterprise entitlement gate',
    ],
    boundary: 'No permission or role was changed.',
    ai: true,
  },
  'ai-credit-usage': {
    title: 'AI Credit Usage',
    category: 'Administration > AI governance',
    route: '/admin/ai',
    components: [
      'credit meter',
      'billing period',
      'Extract info, Categorize, Summarize and Translate examples',
    ],
    boundary:
      'Credit display was observed only. The later AI suggestion preview may affect provider usage and was not treated as a write.',
    ai: true,
  },
  'ai-usage-limits': {
    title: 'AI Usage Limits',
    category: 'Administration > AI governance',
    route: '/admin/ai',
    components: [
      'hard and soft limit controls',
      'user agents',
      'AI workflows',
      'AI columns and automations',
      'connectors',
      'third-party agents',
      'personal API',
      'Vibe',
      'Notetaker',
      'Sidekick',
    ],
    boundary: 'No usage limit was changed.',
    ai: true,
  },
  'ai-agent-governance': {
    title: 'AI Agent Governance',
    category: 'Administration > AI governance',
    route: '/admin/ai',
    components: [
      'All Agents table',
      'privacy risk',
      'model',
      'credits',
      'access columns',
      'empty state',
    ],
    boundary: 'No agent policy or access was changed.',
    ai: true,
  },
  'ai-account-settings': {
    title: 'AI Account Settings',
    category: 'Administration > AI governance',
    route: '/admin/ai',
    components: [
      'Enable monday AI',
      'background optimizations',
      'WhatsApp',
      'Telegram',
      'enforcement banners',
      'enabled switches',
    ],
    boundary: 'No setting was toggled.',
    ai: true,
  },
  'board-options-menu': {
    title: 'Board Options Menu',
    category: 'Board > Options',
    route: 'existing board',
    components: [
      'Power-Ups',
      'AI suggestions',
      'Convert to project',
      'Activity',
      'Discussion',
      'Notifications',
      'Permissions',
      'Settings',
      'More',
      'Archive, delete and trash actions',
    ],
    boundary: 'No board setting or lifecycle action was executed.',
    ai: false,
  },
  'group-actions-menu': {
    title: 'Group Actions Menu',
    category: 'Board > Group actions',
    route: 'existing board',
    components: [
      'collapse',
      'select',
      'add',
      'duplicate',
      'move',
      'rename',
      'color',
      'export',
      'apps',
      'delete and archive',
    ],
    boundary: 'No group action was executed.',
    ai: false,
  },
  'item-actions-menu': {
    title: 'Item Actions Menu',
    category: 'Board > Item actions',
    route: 'existing board',
    components: [
      'open',
      'new tab',
      'copy',
      'move',
      'duplicate',
      'create below',
      'subitem',
      'convert',
      'apps',
      'archive and delete',
    ],
    boundary: 'No item action was executed.',
    ai: false,
  },
  'column-actions-menu': {
    title: 'Column Actions Menu',
    category: 'Board > Column actions',
    route: 'existing board',
    components: [
      'settings',
      'AI-powered actions',
      'Auto-assign labels',
      'Set a custom prompt',
      'filter',
      'sort',
      'collapse',
      'group',
      'duplicate',
      'add',
      'change',
      'save',
      'rename and delete',
    ],
    boundary: 'No column, label or prompt action was executed.',
    ai: false,
  },
  'add-column-menu': {
    title: 'Add Column Menu',
    category: 'Board > Add column',
    route: 'existing board',
    components: [
      'search',
      'describe a column',
      'essential types',
      'super-useful types',
      'Extract info',
      'More columns',
    ],
    boundary: 'No column was added.',
    ai: false,
  },
  'automation-center': {
    title: 'Automation Center',
    category: 'Board > Automate',
    route: 'existing board',
    components: [
      'category navigation',
      'integration recipes',
      'Create from scratch',
      'create with AI entry',
    ],
    boundary: 'No automation or prompt was created.',
    ai: false,
  },
  'ai-automation-templates': {
    title: 'AI Automation Templates',
    category: 'Board > Automate > AI',
    route: 'existing board',
    components: [
      'fill column from item, update, subitem, name, column and email activity',
      'sentiment analysis recipes',
    ],
    boundary: 'No recipe was installed or run.',
    ai: true,
  },
  'board-integrations': {
    title: 'Board Integrations',
    category: 'Board > Integrate',
    route: 'existing board',
    components: [
      'integration count',
      'recommended CRM automations',
      'ZoomInfo',
      'AI Sales Agent',
      'QuickBooks Installed badge',
    ],
    boundary: 'No integration was connected, configured or run.',
    ai: false,
  },
  'board-view-menu': {
    title: 'Board View Menu',
    category: 'Board > Add view',
    route: 'existing board',
    components: [
      'Table',
      'Gantt',
      'Chart',
      'Calendar',
      'Kanban',
      'Doc',
      'File gallery',
      'Form',
      'Dashboard',
      'Build with Vibe',
      'Apps',
      'Explore more',
    ],
    boundary: 'No view or app was added.',
    ai: false,
  },
  'ai-suggestions-preview': {
    title: 'AI Suggestions Preview',
    category: 'Board > Options > AI suggestions',
    route: 'existing board',
    components: [
      'generated suggestion preview',
      'Add column action',
      'Cancel action',
      'Give feedback action',
    ],
    boundary:
      'Provider computation ran automatically after opening the entry. The preview was canceled and no column was added or board data saved.',
    ai: true,
  },
} as const;

export type MondayLeafVariant = keyof typeof mondayLeafFixtures;

export const mondayLeafEntries = Object.entries(mondayLeafFixtures).map(([variant, fixture]) => ({
  id: `monday-${variant}`,
  variant: variant as MondayLeafVariant,
  description: fixture.title,
}));
