import { useState } from 'react'; import styles from '../semrush-action-primitives.module.css';
export type SemrushDialogKind = 'crawl-limit' | 'profile-limit' | 'target-change';
export interface SemrushWarningQuotaDialogProps { kind?: SemrushDialogKind; initialOpen?: boolean; }
const dialogCopy = {
  'crawl-limit': { title: 'Crawl limit reached', body: 'Only the configured maximum number of pages is represented. Coverage may be incomplete.', action: 'Change page limit' },
  'profile-limit': { title: 'Brand profile limit reached', body: 'The observed account had used 1 of 1 tracked brand profiles.', action: 'Analyze more brands' },
  'target-change': { title: 'Start a new analysis?', body: 'Applying a new target starts another analysis and pauses collection for the current target.', action: 'Apply target' },
} as const;
export function SemrushWarningQuotaDialog({ kind = 'crawl-limit', initialOpen = true }: SemrushWarningQuotaDialogProps) { const [open, setOpen] = useState(initialOpen); const [status, setStatus] = useState(''); const copy = dialogCopy[kind]; if (!open) return <div className={styles.stage}><section className={styles.card} aria-label="Warning dialog specimen"><button className={`${styles.button} ${styles.secondary}`} type="button" onClick={() => setOpen(true)}>Open {copy.title}</button>{status && <p className={styles.status} role="status">{status}</p>}</section></div>; return <div className={styles.dialogBackdrop}><section className={styles.dialog} role="dialog" aria-modal="true" aria-labelledby={`semrush-warning-${kind}`}><div className={styles.dialogTitle}><h3 id={`semrush-warning-${kind}`}>{copy.title}</h3><button type="button" aria-label="Close dialog" onClick={() => setOpen(false)}>×</button></div><div className={styles.modalBody}><span className={styles.warningIcon} aria-hidden="true">!</span><p>{copy.body}</p></div><div className={styles.actions}><button className={`${styles.button} ${styles.primary}`} type="button" onClick={() => setStatus(`${copy.action} needs verification.`)} disabled>{copy.action} · needs verification</button><button className={`${styles.button} ${styles.secondary}`} type="button" onClick={() => { setOpen(false); setStatus('Dialog dismissed without changes.'); }}>Cancel</button></div></section></div>; }
