import type { PreviewConfig, PreviewRegistry } from '../types';
import { WixPreview, type WixVariant } from './WixPreview';

const config: PreviewConfig = {
  viewports: [
    { id: 'desktop', label: 'Desktop', width: 1180 },
    { id: 'narrow', label: 'Narrow', width: 720 },
  ],
  toggles: [{ id: 'disabled', label: 'Fixture', onLabel: 'Disabled', offLabel: 'Enabled' }],
};

const entries: Array<[string, WixVariant, string, Array<[string, string, string?]>]> = [
  ['wix-dashboard-application-shell', 'home-dashboard', 'Dashboard application shell', [['default', 'Observed shell']]],
  ['wix-setup-checklist', 'setup-checklist', 'Business setup checklist', [['default', 'Observed checklist']]],
  ['wix-quick-actions-catalog', 'quick-actions', 'Quick Actions catalogue', [['default', 'Observed catalogue']]],
  ['wix-analytics-highlights', 'analytics-highlights', 'Analytics Highlights zero state', [['default', 'Observed highlights']]],
  ['wix-ai-site-design-entry', 'ai-site-design', 'AI site-design entry', [['default', 'Observed entry screen']]],
  ['wix-template-gallery-and-responsive-preview', 'template-gallery', 'Template gallery and responsive preview', [['default', 'Observed gallery and preview']]],
  ['wix-realtime-analytics', 'realtime-analytics', 'Real-time Analytics zero state', [['recent', 'Visitors in last 30 minutes'], ['live', 'Live visitors tab', 'live']]],
  ['wix-traffic-overview', 'traffic-overview', 'Traffic Overview zero state', [['default', 'Observed overview'], ['date-open', 'Date range open', 'date-open']]],
  ['wix-analytics-date-range', 'analytics-date-range', 'Analytics date-range popover', [['open', 'Observed open popover']]],
  ['wix-seo-geo-overview', 'seo-geo-overview', 'SEO and GEO overview', [['default', 'Observed overview'], ['help-open', 'Help menu open', 'help-open']]],
  ['wix-seo-help-menu', 'seo-help-menu', 'SEO contextual help menu', [['open', 'Observed menu open']]],
  ['wix-contacts-workspace', 'contacts-workspace', 'Contacts workspace with fictional row', [['default', 'Fictional contact list'], ['create-open', 'Create menu open', 'create-open']]],
  ['wix-contact-create-menu', 'contact-create-menu', 'Contact Create New disclosure', [['open', 'Observed action choices']]],
  ['wix-manage-apps', 'manage-apps', 'Manage Apps workspace', [['default', 'Observed app list'], ['drawer-open', 'App actions open', 'drawer-open']]],
  ['wix-installed-app-actions-drawer', 'installed-app-actions', 'Installed-app actions drawer', [['open', 'Observed drawer open']]],
  ['wix-behavior-overview', 'behavior-overview', 'Behavior Overview zero state', [['default', 'Observed overview']]],
  ['wix-marketing-overview', 'marketing-overview', 'Marketing Overview zero state', [['default', 'Observed overview']]],
  ['wix-session-recordings-gate', 'session-recordings', 'Session Recordings plan gate', [['default', 'Observed upgrade gate']]],
  ['wix-insights-benchmarks', 'insights-benchmarks', 'Insights and Benchmarks analysis state', [['default', 'Observed analysis state']]],
  ['wix-home-dashboard', 'home-dashboard', 'Home dashboard free-plan state', [['default', 'Observed dashboard']]],
  ['wix-inbox-setup', 'inbox', 'Inbox setup and spam state', [['default', 'Observed setup state']]],
  ['wix-automations-workspace', 'automations', 'Automations first-run workspace', [['default', 'Observed workspace']]],
  ['wix-forms-submissions', 'forms-submissions', 'Forms and Submissions first-run state', [['default', 'Observed workspace']]],
  ['wix-website-overview-and-utility-menus', 'website-overview', 'Website Overview unpublished state', [['default', 'Observed overview']]],
  ['wix-site-speed-analysis', 'site-speed', 'Site Speed analysis state', [['default', 'Observed analysis state']]],
  ['wix-uptime-security-gate', 'uptime-security', 'Uptime and Security publish gate', [['default', 'Observed publish gate']]],
  ['wix-mobile-app-overview', 'mobile-app', 'Mobile App setup workspace', [['default', 'Observed workspace']]],
  ['wix-symphony-agent-entry', 'symphony', 'Symphony agent entry screen', [['default', 'Observed entry screen']]],
  ['wix-design-agent-entry', 'design-agent', 'Wixel design agent entry screen', [['default', 'Observed entry screen']]],
  ['wix-getting-paid-overview', 'getting-paid', 'Getting Paid setup screen', [['default', 'Observed setup screen']]],
  ['wix-payments-plan-gate', 'payments', 'Payments plan gate', [['default', 'Observed upgrade gate']]],
  ['wix-receipts-empty-state', 'receipts', 'Receipts empty state', [['default', 'Observed empty state']]],
  ['wix-point-of-sale-entry', 'point-of-sale', 'Point of Sale setup entry', [['default', 'Observed setup entry']]],
  ['wix-settings-and-seo-workspace', 'settings-overview', 'Settings overview taxonomy', [['default', 'Observed settings overview']]],
  ['wix-app-market-entry', 'app-market', 'App Market featured entry', [['default', 'Observed featured entry']]],
  ['wix-marketing-agent-loading', 'loading-shell', 'Marketing Agent loading shell', [['loading', 'Observed bounded loading state', 'marketing-agent']]],
  ['wix-portfolio-projects-loading', 'loading-shell', 'Portfolio Projects loading shell', [['loading', 'Observed bounded loading state', 'portfolio-projects']]],
  ['wix-portfolio-collections-loading', 'loading-shell', 'Portfolio Collections loading shell', [['loading', 'Observed bounded loading state', 'portfolio-collections']]],
  ['wix-portfolio-integrations-loading', 'loading-shell', 'Portfolio Integrations loading shell', [['loading', 'Observed bounded loading state', 'portfolio-integrations']]],
  ['wix-logo-brand-loading', 'loading-shell', 'Logo and Brand loading shell', [['loading', 'Observed bounded loading state', 'logo-brand']]],
  ['wix-hopp-loading', 'loading-shell', 'Hopp loading shell', [['loading', 'Observed bounded loading state', 'hopp']]],
  ['wix-all-reports-loading', 'loading-shell', 'All Reports loading shell', [['loading', 'Observed bounded loading state', 'all-reports']]],
  ['wix-sales-overview-loading', 'loading-shell', 'Sales Overview loading shell', [['loading', 'Observed bounded loading state', 'sales-overview']]],
  ['wix-catalog-loading', 'loading-shell', 'Catalog loading shell', [['loading', 'Observed bounded loading state', 'catalog']]],
  ['wix-pos-checkout-entry', 'pos-checkout', 'Point of Sale checkout entry', [['default', 'Observed setup entry']]],
  ['wix-business-email-domain-gate', 'business-email', 'Business Email domain gate', [['default', 'Observed domain gate']]],
];

export const wixPreviews: PreviewRegistry = Object.fromEntries(entries.map(([id, variant, label, states]) => [id, {
  type: 'reconstructed',
  Component: WixPreview,
  label: 'Authenticated observation reconstructed with fictional local data',
  evidence: 'Authenticated Wix dashboard observed 2026-10-07. Fixtures use fictional local data and send no Wix request. AI execution, Google connection, form or contact creation, editor setup, app installation, messaging, payment setup, point-of-sale setup, upgrade, domain connection, publication, support, deletion and persistence remain unverified.',
  runtimeVerified: true,
  fixtures: states.map(([stateId, title, initialState]) => ({ id: stateId, title, props: { variant, ...(initialState ? { initialState } : {}) } })),
  config,
  propsSchema: [
    { name: 'variant', type: 'WixVariant', required: true, description: `Selects the ${label.toLowerCase()} reconstruction.` },
    { name: 'initialState', type: 'string', required: false, description: 'Starts the fixture in an observed disclosure state.' },
    { name: 'disabled', type: 'boolean', required: false, description: 'Disables this fictional local fixture.' },
  ],
}]));
